set shell := ["bash", "-cu"]

default:
    just --list

clean:
    (cd tests && lake clean)
    (cd table-generators && lake clean)
    (cd lib && lake clean)
    (cd common && lake clean)
    (cd lean-scripts && lake clean)
    rm -rf table-generators/data-ucd
    rm -rf lib/data-table
    # delete files autogenerated by makeCLib.lean
    rm -f lib/UnicodeCLib/prop.c lib/UnicodeCLib/case.c lib/UnicodeCLib/script.c

download-ucd:
    node scripts/download_unicode_data.ts

docs-readme:
    ln -sfn ../README.md docs/README.md

ucd-usage-status:
    node scripts/ucd_txt_usage.ts

generate-do-not-emit:
    node scripts/generate_do_not_emit.ts

generate-names-list:
    node scripts/generate_names_list.ts

table-provenance:
    node scripts/ucd_table_provenance.ts

tables:
    cd table-generators && lake exe makeTables

clib:
    cd table-generators && lake exe makeCLib

build:
    (cd common && lake build --wfail)
    (cd lib && lake build --wfail)
    (cd table-generators && lake build --wfail)
    (cd tests && lake build --wfail)
    (cd lean-scripts && lake build --wfail)

test:
    cd tests && lake test

check-ucd-text:
    node scripts/check_ucd_text_not_baked.ts

all: tables clib build test
