/- This file is generated by table-generators/makeTablesForLookup. -/
module

@[expose] public section

namespace Unicode.TableLookupTables.BlockName

abbrev start : UInt32 := 0x0000

abbrev «end» : UInt32 := 0x10FFFF

abbrev BetweenOrEqStartEnd (v : UInt32) : Prop := start ≤ v ∧ v ≤ «end»

@[inline_if_reduce, reducible]
def getInsideSparseRangeValueTable (v : UInt32) (_h : BetweenOrEqStartEnd v) : Option String :=
  if v < 0x10300 then
    if v < 0x25A0 then
      if v < 0x16A0 then
        if v < 0x08A0 then
          if v < 0x0530 then
            if v < 0x02B0 then
              if v < 0x0100 then
                if v < 0x0080 then
                  if 0x0000 ≤ v ∧ v ≤ 0x007F then some ("Basic Latin") else none
                else if 0x00FF < v then
                  none
                else some ("Latin-1 Supplement")
              else if 0x017F < v then
                if v < 0x0250 then
                  if 0x0180 ≤ v ∧ v ≤ 0x024F then some ("Latin Extended-B") else none
                else if 0x02AF < v then
                  none
                else some ("IPA Extensions")
              else some ("Latin Extended-A")
            else if 0x02FF < v then
              if v < 0x0400 then
                if v < 0x0370 then
                  if 0x0300 ≤ v ∧ v ≤ 0x036F then some ("Combining Diacritical Marks") else none
                else if 0x03FF < v then
                  none
                else some ("Greek and Coptic")
              else if 0x04FF < v then
                if 0x0500 ≤ v ∧ v ≤ 0x052F then some ("Cyrillic Supplement") else none
              else some ("Cyrillic")
            else some ("Spacing Modifier Letters")
          else if 0x058F < v then
            if v < 0x07C0 then
              if v < 0x0700 then
                if v < 0x0600 then
                  if 0x0590 ≤ v ∧ v ≤ 0x05FF then some ("Hebrew") else none
                else if 0x06FF < v then
                  none
                else some ("Arabic")
              else if 0x074F < v then
                if v < 0x0780 then
                  if 0x0750 ≤ v ∧ v ≤ 0x077F then some ("Arabic Supplement") else none
                else if 0x07BF < v then
                  none
                else some ("Thaana")
              else some ("Syriac")
            else if 0x07FF < v then
              if v < 0x0860 then
                if v < 0x0840 then
                  if 0x0800 ≤ v ∧ v ≤ 0x083F then some ("Samaritan") else none
                else if 0x085F < v then
                  none
                else some ("Mandaic")
              else if 0x086F < v then
                if 0x0870 ≤ v ∧ v ≤ 0x089F then some ("Arabic Extended-B") else none
              else some ("Syriac Supplement")
            else some ("NKo")
          else some ("Armenian")
        else if 0x08FF < v then
          if v < 0x0E00 then
            if v < 0x0B80 then
              if v < 0x0A00 then
                if v < 0x0980 then
                  if 0x0900 ≤ v ∧ v ≤ 0x097F then some ("Devanagari") else none
                else if 0x09FF < v then
                  none
                else some ("Bengali")
              else if 0x0A7F < v then
                if v < 0x0B00 then
                  if 0x0A80 ≤ v ∧ v ≤ 0x0AFF then some ("Gujarati") else none
                else if 0x0B7F < v then
                  none
                else some ("Oriya")
              else some ("Gurmukhi")
            else if 0x0BFF < v then
              if v < 0x0D00 then
                if v < 0x0C80 then
                  if 0x0C00 ≤ v ∧ v ≤ 0x0C7F then some ("Telugu") else none
                else if 0x0CFF < v then
                  none
                else some ("Kannada")
              else if 0x0D7F < v then
                if 0x0D80 ≤ v ∧ v ≤ 0x0DFF then some ("Sinhala") else none
              else some ("Malayalam")
            else some ("Tamil")
          else if 0x0E7F < v then
            if v < 0x1200 then
              if v < 0x1000 then
                if v < 0x0F00 then
                  if 0x0E80 ≤ v ∧ v ≤ 0x0EFF then some ("Lao") else none
                else if 0x0FFF < v then
                  none
                else some ("Tibetan")
              else if 0x109F < v then
                if v < 0x1100 then
                  if 0x10A0 ≤ v ∧ v ≤ 0x10FF then some ("Georgian") else none
                else if 0x11FF < v then
                  none
                else some ("Hangul Jamo")
              else some ("Myanmar")
            else if 0x137F < v then
              if v < 0x1400 then
                if v < 0x13A0 then
                  if 0x1380 ≤ v ∧ v ≤ 0x139F then some ("Ethiopic Supplement") else none
                else if 0x13FF < v then
                  none
                else some ("Cherokee")
              else if 0x167F < v then
                if 0x1680 ≤ v ∧ v ≤ 0x169F then some ("Ogham") else none
              else some ("Unified Canadian Aboriginal Syllabics")
            else some ("Ethiopic")
          else some ("Thai")
        else some ("Arabic Extended-A")
      else if 0x16FF < v then
        if v < 0x1CC0 then
          if v < 0x19E0 then
            if v < 0x1800 then
              if v < 0x1740 then
                if v < 0x1720 then
                  if 0x1700 ≤ v ∧ v ≤ 0x171F then some ("Tagalog") else none
                else if 0x173F < v then
                  none
                else some ("Hanunoo")
              else if 0x175F < v then
                if v < 0x1780 then
                  if 0x1760 ≤ v ∧ v ≤ 0x177F then some ("Tagbanwa") else none
                else if 0x17FF < v then
                  none
                else some ("Khmer")
              else some ("Buhid")
            else if 0x18AF < v then
              if v < 0x1950 then
                if v < 0x1900 then
                  if 0x18B0 ≤ v ∧ v ≤ 0x18FF then some ("Unified Canadian Aboriginal Syllabics Extended") else none
                else if 0x194F < v then
                  none
                else some ("Limbu")
              else if 0x197F < v then
                if 0x1980 ≤ v ∧ v ≤ 0x19DF then some ("New Tai Lue") else none
              else some ("Tai Le")
            else some ("Mongolian")
          else if 0x19FF < v then
            if v < 0x1BC0 then
              if v < 0x1AB0 then
                if v < 0x1A20 then
                  if 0x1A00 ≤ v ∧ v ≤ 0x1A1F then some ("Buginese") else none
                else if 0x1AAF < v then
                  none
                else some ("Tai Tham")
              else if 0x1AFF < v then
                if v < 0x1B80 then
                  if 0x1B00 ≤ v ∧ v ≤ 0x1B7F then some ("Balinese") else none
                else if 0x1BBF < v then
                  none
                else some ("Sundanese")
              else some ("Combining Diacritical Marks Extended")
            else if 0x1BFF < v then
              if v < 0x1C80 then
                if v < 0x1C50 then
                  if 0x1C00 ≤ v ∧ v ≤ 0x1C4F then some ("Lepcha") else none
                else if 0x1C7F < v then
                  none
                else some ("Ol Chiki")
              else if 0x1C8F < v then
                if 0x1C90 ≤ v ∧ v ≤ 0x1CBF then some ("Georgian Extended") else none
              else some ("Cyrillic Extended-C")
            else some ("Batak")
          else some ("Khmer Symbols")
        else if 0x1CCF < v then
          if v < 0x2100 then
            if v < 0x1F00 then
              if v < 0x1D80 then
                if v < 0x1D00 then
                  if 0x1CD0 ≤ v ∧ v ≤ 0x1CFF then some ("Vedic Extensions") else none
                else if 0x1D7F < v then
                  none
                else some ("Phonetic Extensions")
              else if 0x1DBF < v then
                if v < 0x1E00 then
                  if 0x1DC0 ≤ v ∧ v ≤ 0x1DFF then some ("Combining Diacritical Marks Supplement") else none
                else if 0x1EFF < v then
                  none
                else some ("Latin Extended Additional")
              else some ("Phonetic Extensions Supplement")
            else if 0x1FFF < v then
              if v < 0x20A0 then
                if v < 0x2070 then
                  if 0x2000 ≤ v ∧ v ≤ 0x206F then some ("General Punctuation") else none
                else if 0x209F < v then
                  none
                else some ("Superscripts and Subscripts")
              else if 0x20CF < v then
                if 0x20D0 ≤ v ∧ v ≤ 0x20FF then some ("Combining Diacritical Marks for Symbols") else none
              else some ("Currency Symbols")
            else some ("Greek Extended")
          else if 0x214F < v then
            if v < 0x2400 then
              if v < 0x2200 then
                if v < 0x2190 then
                  if 0x2150 ≤ v ∧ v ≤ 0x218F then some ("Number Forms") else none
                else if 0x21FF < v then
                  none
                else some ("Arrows")
              else if 0x22FF < v then
                if 0x2300 ≤ v ∧ v ≤ 0x23FF then some ("Miscellaneous Technical") else none
              else some ("Mathematical Operators")
            else if 0x243F < v then
              if v < 0x2500 then
                if v < 0x2460 then
                  if 0x2440 ≤ v ∧ v ≤ 0x245F then some ("Optical Character Recognition") else none
                else if 0x24FF < v then
                  none
                else some ("Enclosed Alphanumerics")
              else if 0x257F < v then
                if 0x2580 ≤ v ∧ v ≤ 0x259F then some ("Block Elements") else none
              else some ("Box Drawing")
            else some ("Control Pictures")
          else some ("Letterlike Symbols")
        else some ("Sundanese Supplement")
      else some ("Runic")
    else if 0x25FF < v then
      if v < 0xA830 then
        if v < 0x3040 then
          if v < 0x2C60 then
            if v < 0x2900 then
              if v < 0x27C0 then
                if v < 0x2700 then
                  if 0x2600 ≤ v ∧ v ≤ 0x26FF then some ("Miscellaneous Symbols") else none
                else if 0x27BF < v then
                  none
                else some ("Dingbats")
              else if 0x27EF < v then
                if v < 0x2800 then
                  if 0x27F0 ≤ v ∧ v ≤ 0x27FF then some ("Supplemental Arrows-A") else none
                else if 0x28FF < v then
                  none
                else some ("Braille Patterns")
              else some ("Miscellaneous Mathematical Symbols-A")
            else if 0x297F < v then
              if v < 0x2B00 then
                if v < 0x2A00 then
                  if 0x2980 ≤ v ∧ v ≤ 0x29FF then some ("Miscellaneous Mathematical Symbols-B") else none
                else if 0x2AFF < v then
                  none
                else some ("Supplemental Mathematical Operators")
              else if 0x2BFF < v then
                if 0x2C00 ≤ v ∧ v ≤ 0x2C5F then some ("Glagolitic") else none
              else some ("Miscellaneous Symbols and Arrows")
            else some ("Supplemental Arrows-B")
          else if 0x2C7F < v then
            if v < 0x2E00 then
              if v < 0x2D30 then
                if v < 0x2D00 then
                  if 0x2C80 ≤ v ∧ v ≤ 0x2CFF then some ("Coptic") else none
                else if 0x2D2F < v then
                  none
                else some ("Georgian Supplement")
              else if 0x2D7F < v then
                if v < 0x2DE0 then
                  if 0x2D80 ≤ v ∧ v ≤ 0x2DDF then some ("Ethiopic Extended") else none
                else if 0x2DFF < v then
                  none
                else some ("Cyrillic Extended-A")
              else some ("Tifinagh")
            else if 0x2E7F < v then
              if v < 0x2FF0 then
                if v < 0x2F00 then
                  if 0x2E80 ≤ v ∧ v ≤ 0x2EFF then some ("CJK Radicals Supplement") else none
                else if 0x2FDF < v then
                  none
                else some ("Kangxi Radicals")
              else if 0x2FFF < v then
                if 0x3000 ≤ v ∧ v ≤ 0x303F then some ("CJK Symbols and Punctuation") else none
              else some ("Ideographic Description Characters")
            else some ("Supplemental Punctuation")
          else some ("Latin Extended-C")
        else if 0x309F < v then
          if v < 0x4DC0 then
            if v < 0x31C0 then
              if v < 0x3130 then
                if v < 0x3100 then
                  if 0x30A0 ≤ v ∧ v ≤ 0x30FF then some ("Katakana") else none
                else if 0x312F < v then
                  none
                else some ("Bopomofo")
              else if 0x318F < v then
                if v < 0x31A0 then
                  if 0x3190 ≤ v ∧ v ≤ 0x319F then some ("Kanbun") else none
                else if 0x31BF < v then
                  none
                else some ("Bopomofo Extended")
              else some ("Hangul Compatibility Jamo")
            else if 0x31EF < v then
              if v < 0x3300 then
                if v < 0x3200 then
                  if 0x31F0 ≤ v ∧ v ≤ 0x31FF then some ("Katakana Phonetic Extensions") else none
                else if 0x32FF < v then
                  none
                else some ("Enclosed CJK Letters and Months")
              else if 0x33FF < v then
                if 0x3400 ≤ v ∧ v ≤ 0x4DBF then some ("CJK Unified Ideographs Extension A") else none
              else some ("CJK Compatibility")
            else some ("CJK Strokes")
          else if 0x4DFF < v then
            if v < 0xA640 then
              if v < 0xA490 then
                if v < 0xA000 then
                  if 0x4E00 ≤ v ∧ v ≤ 0x9FFF then some ("CJK Unified Ideographs") else none
                else if 0xA48F < v then
                  none
                else some ("Yi Syllables")
              else if 0xA4CF < v then
                if v < 0xA500 then
                  if 0xA4D0 ≤ v ∧ v ≤ 0xA4FF then some ("Lisu") else none
                else if 0xA63F < v then
                  none
                else some ("Vai")
              else some ("Yi Radicals")
            else if 0xA69F < v then
              if v < 0xA720 then
                if v < 0xA700 then
                  if 0xA6A0 ≤ v ∧ v ≤ 0xA6FF then some ("Bamum") else none
                else if 0xA71F < v then
                  none
                else some ("Modifier Tone Letters")
              else if 0xA7FF < v then
                if 0xA800 ≤ v ∧ v ≤ 0xA82F then some ("Syloti Nagri") else none
              else some ("Latin Extended-D")
            else some ("Cyrillic Extended-B")
          else some ("Yijing Hexagram Symbols")
        else some ("Hiragana")
      else if 0xA83F < v then
        if v < 0xE000 then
          if v < 0xAA80 then
            if v < 0xA960 then
              if v < 0xA8E0 then
                if v < 0xA880 then
                  if 0xA840 ≤ v ∧ v ≤ 0xA87F then some ("Phags-pa") else none
                else if 0xA8DF < v then
                  none
                else some ("Saurashtra")
              else if 0xA8FF < v then
                if v < 0xA930 then
                  if 0xA900 ≤ v ∧ v ≤ 0xA92F then some ("Kayah Li") else none
                else if 0xA95F < v then
                  none
                else some ("Rejang")
              else some ("Devanagari Extended")
            else if 0xA97F < v then
              if v < 0xAA00 then
                if v < 0xA9E0 then
                  if 0xA980 ≤ v ∧ v ≤ 0xA9DF then some ("Javanese") else none
                else if 0xA9FF < v then
                  none
                else some ("Myanmar Extended-B")
              else if 0xAA5F < v then
                if 0xAA60 ≤ v ∧ v ≤ 0xAA7F then some ("Myanmar Extended-A") else none
              else some ("Cham")
            else some ("Hangul Jamo Extended-A")
          else if 0xAADF < v then
            if v < 0xAC00 then
              if v < 0xAB30 then
                if v < 0xAB00 then
                  if 0xAAE0 ≤ v ∧ v ≤ 0xAAFF then some ("Meetei Mayek Extensions") else none
                else if 0xAB2F < v then
                  none
                else some ("Ethiopic Extended-A")
              else if 0xAB6F < v then
                if v < 0xABC0 then
                  if 0xAB70 ≤ v ∧ v ≤ 0xABBF then some ("Cherokee Supplement") else none
                else if 0xABFF < v then
                  none
                else some ("Meetei Mayek")
              else some ("Latin Extended-E")
            else if 0xD7AF < v then
              if v < 0xDB80 then
                if v < 0xD800 then
                  if 0xD7B0 ≤ v ∧ v ≤ 0xD7FF then some ("Hangul Jamo Extended-B") else none
                else if 0xDB7F < v then
                  none
                else some ("High Surrogates")
              else if 0xDBFF < v then
                if 0xDC00 ≤ v ∧ v ≤ 0xDFFF then some ("Low Surrogates") else none
              else some ("High Private Use Surrogates")
            else some ("Hangul Syllables")
          else some ("Tai Viet")
        else if 0xF8FF < v then
          if v < 0xFFF0 then
            if v < 0xFE20 then
              if v < 0xFB50 then
                if v < 0xFB00 then
                  if 0xF900 ≤ v ∧ v ≤ 0xFAFF then some ("CJK Compatibility Ideographs") else none
                else if 0xFB4F < v then
                  none
                else some ("Alphabetic Presentation Forms")
              else if 0xFDFF < v then
                if v < 0xFE10 then
                  if 0xFE00 ≤ v ∧ v ≤ 0xFE0F then some ("Variation Selectors") else none
                else if 0xFE1F < v then
                  none
                else some ("Vertical Forms")
              else some ("Arabic Presentation Forms-A")
            else if 0xFE2F < v then
              if v < 0xFE70 then
                if v < 0xFE50 then
                  if 0xFE30 ≤ v ∧ v ≤ 0xFE4F then some ("CJK Compatibility Forms") else none
                else if 0xFE6F < v then
                  none
                else some ("Small Form Variants")
              else if 0xFEFF < v then
                if 0xFF00 ≤ v ∧ v ≤ 0xFFEF then some ("Halfwidth and Fullwidth Forms") else none
              else some ("Arabic Presentation Forms-B")
            else some ("Combining Half Marks")
          else if 0xFFFF < v then
            if v < 0x10190 then
              if v < 0x10100 then
                if v < 0x10080 then
                  if 0x10000 ≤ v ∧ v ≤ 0x1007F then some ("Linear B Syllabary") else none
                else if 0x100FF < v then
                  none
                else some ("Linear B Ideograms")
              else if 0x1013F < v then
                if 0x10140 ≤ v ∧ v ≤ 0x1018F then some ("Ancient Greek Numbers") else none
              else some ("Aegean Numbers")
            else if 0x101CF < v then
              if v < 0x102A0 then
                if v < 0x10280 then
                  if 0x101D0 ≤ v ∧ v ≤ 0x101FF then some ("Phaistos Disc") else none
                else if 0x1029F < v then
                  none
                else some ("Lycian")
              else if 0x102DF < v then
                if 0x102E0 ≤ v ∧ v ≤ 0x102FF then some ("Coptic Epact Numbers") else none
              else some ("Carian")
            else some ("Ancient Symbols")
          else some ("Specials")
        else some ("Private Use Area")
      else some ("Common Indic Number Forms")
    else some ("Geometric Shapes")
  else if 0x1032F < v then
    if v < 0x12480 then
      if v < 0x10FE0 then
        if v < 0x10940 then
          if v < 0x10570 then
            if v < 0x10450 then
              if v < 0x10380 then
                if v < 0x10350 then
                  if 0x10330 ≤ v ∧ v ≤ 0x1034F then some ("Gothic") else none
                else if 0x1037F < v then
                  none
                else some ("Old Permic")
              else if 0x1039F < v then
                if v < 0x10400 then
                  if 0x103A0 ≤ v ∧ v ≤ 0x103DF then some ("Old Persian") else none
                else if 0x1044F < v then
                  none
                else some ("Deseret")
              else some ("Ugaritic")
            else if 0x1047F < v then
              if v < 0x10500 then
                if v < 0x104B0 then
                  if 0x10480 ≤ v ∧ v ≤ 0x104AF then some ("Osmanya") else none
                else if 0x104FF < v then
                  none
                else some ("Osage")
              else if 0x1052F < v then
                if 0x10530 ≤ v ∧ v ≤ 0x1056F then some ("Caucasian Albanian") else none
              else some ("Elbasan")
            else some ("Shavian")
          else if 0x105BF < v then
            if v < 0x10860 then
              if v < 0x10780 then
                if v < 0x10600 then
                  if 0x105C0 ≤ v ∧ v ≤ 0x105FF then some ("Todhri") else none
                else if 0x1077F < v then
                  none
                else some ("Linear A")
              else if 0x107BF < v then
                if v < 0x10840 then
                  if 0x10800 ≤ v ∧ v ≤ 0x1083F then some ("Cypriot Syllabary") else none
                else if 0x1085F < v then
                  none
                else some ("Imperial Aramaic")
              else some ("Latin Extended-F")
            else if 0x1087F < v then
              if v < 0x10900 then
                if v < 0x108E0 then
                  if 0x10880 ≤ v ∧ v ≤ 0x108AF then some ("Nabataean") else none
                else if 0x108FF < v then
                  none
                else some ("Hatran")
              else if 0x1091F < v then
                if 0x10920 ≤ v ∧ v ≤ 0x1093F then some ("Lydian") else none
              else some ("Phoenician")
            else some ("Palmyrene")
          else some ("Vithkuqi")
        else if 0x1095F < v then
          if v < 0x10C00 then
            if v < 0x10AC0 then
              if v < 0x10A00 then
                if v < 0x109A0 then
                  if 0x10980 ≤ v ∧ v ≤ 0x1099F then some ("Meroitic Hieroglyphs") else none
                else if 0x109FF < v then
                  none
                else some ("Meroitic Cursive")
              else if 0x10A5F < v then
                if v < 0x10A80 then
                  if 0x10A60 ≤ v ∧ v ≤ 0x10A7F then some ("Old South Arabian") else none
                else if 0x10A9F < v then
                  none
                else some ("Old North Arabian")
              else some ("Kharoshthi")
            else if 0x10AFF < v then
              if v < 0x10B60 then
                if v < 0x10B40 then
                  if 0x10B00 ≤ v ∧ v ≤ 0x10B3F then some ("Avestan") else none
                else if 0x10B5F < v then
                  none
                else some ("Inscriptional Parthian")
              else if 0x10B7F < v then
                if 0x10B80 ≤ v ∧ v ≤ 0x10BAF then some ("Psalter Pahlavi") else none
              else some ("Inscriptional Pahlavi")
            else some ("Manichaean")
          else if 0x10C4F < v then
            if v < 0x10EC0 then
              if v < 0x10D40 then
                if v < 0x10D00 then
                  if 0x10C80 ≤ v ∧ v ≤ 0x10CFF then some ("Old Hungarian") else none
                else if 0x10D3F < v then
                  none
                else some ("Hanifi Rohingya")
              else if 0x10D8F < v then
                if v < 0x10E80 then
                  if 0x10E60 ≤ v ∧ v ≤ 0x10E7F then some ("Rumi Numeral Symbols") else none
                else if 0x10EBF < v then
                  none
                else some ("Yezidi")
              else some ("Garay")
            else if 0x10EFF < v then
              if v < 0x10F70 then
                if v < 0x10F30 then
                  if 0x10F00 ≤ v ∧ v ≤ 0x10F2F then some ("Old Sogdian") else none
                else if 0x10F6F < v then
                  none
                else some ("Sogdian")
              else if 0x10FAF < v then
                if 0x10FB0 ≤ v ∧ v ≤ 0x10FDF then some ("Chorasmian") else none
              else some ("Old Uyghur")
            else some ("Arabic Extended-C")
          else some ("Old Turkic")
        else some ("Sidetic")
      else if 0x10FFF < v then
        if v < 0x118A0 then
          if v < 0x11300 then
            if v < 0x11180 then
              if v < 0x110D0 then
                if v < 0x11080 then
                  if 0x11000 ≤ v ∧ v ≤ 0x1107F then some ("Brahmi") else none
                else if 0x110CF < v then
                  none
                else some ("Kaithi")
              else if 0x110FF < v then
                if v < 0x11150 then
                  if 0x11100 ≤ v ∧ v ≤ 0x1114F then some ("Chakma") else none
                else if 0x1117F < v then
                  none
                else some ("Mahajani")
              else some ("Sora Sompeng")
            else if 0x111DF < v then
              if v < 0x11280 then
                if v < 0x11200 then
                  if 0x111E0 ≤ v ∧ v ≤ 0x111FF then some ("Sinhala Archaic Numbers") else none
                else if 0x1124F < v then
                  none
                else some ("Khojki")
              else if 0x112AF < v then
                if 0x112B0 ≤ v ∧ v ≤ 0x112FF then some ("Khudawadi") else none
              else some ("Multani")
            else some ("Sharada")
          else if 0x1137F < v then
            if v < 0x11660 then
              if v < 0x11480 then
                if v < 0x11400 then
                  if 0x11380 ≤ v ∧ v ≤ 0x113FF then some ("Tulu-Tigalari") else none
                else if 0x1147F < v then
                  none
                else some ("Newa")
              else if 0x114DF < v then
                if v < 0x11600 then
                  if 0x11580 ≤ v ∧ v ≤ 0x115FF then some ("Siddham") else none
                else if 0x1165F < v then
                  none
                else some ("Modi")
              else some ("Tirhuta")
            else if 0x1167F < v then
              if v < 0x11700 then
                if v < 0x116D0 then
                  if 0x11680 ≤ v ∧ v ≤ 0x116CF then some ("Takri") else none
                else if 0x116FF < v then
                  none
                else some ("Myanmar Extended-C")
              else if 0x1174F < v then
                if 0x11800 ≤ v ∧ v ≤ 0x1184F then some ("Dogra") else none
              else some ("Ahom")
            else some ("Mongolian Supplement")
          else some ("Grantha")
        else if 0x118FF < v then
          if v < 0x11C70 then
            if v < 0x11AC0 then
              if v < 0x11A00 then
                if v < 0x119A0 then
                  if 0x11900 ≤ v ∧ v ≤ 0x1195F then some ("Dives Akuru") else none
                else if 0x119FF < v then
                  none
                else some ("Nandinagari")
              else if 0x11A4F < v then
                if v < 0x11AB0 then
                  if 0x11A50 ≤ v ∧ v ≤ 0x11AAF then some ("Soyombo") else none
                else if 0x11ABF < v then
                  none
                else some ("Unified Canadian Aboriginal Syllabics Extended-A")
              else some ("Zanabazar Square")
            else if 0x11AFF < v then
              if v < 0x11BC0 then
                if v < 0x11B60 then
                  if 0x11B00 ≤ v ∧ v ≤ 0x11B5F then some ("Devanagari Extended-A") else none
                else if 0x11B7F < v then
                  none
                else some ("Sharada Supplement")
              else if 0x11BFF < v then
                if 0x11C00 ≤ v ∧ v ≤ 0x11C6F then some ("Bhaiksuki") else none
              else some ("Sunuwar")
            else some ("Pau Cin Hau")
          else if 0x11CBF < v then
            if v < 0x11F00 then
              if v < 0x11DB0 then
                if v < 0x11D60 then
                  if 0x11D00 ≤ v ∧ v ≤ 0x11D5F then some ("Masaram Gondi") else none
                else if 0x11DAF < v then
                  none
                else some ("Gunjala Gondi")
              else if 0x11DEF < v then
                if 0x11EE0 ≤ v ∧ v ≤ 0x11EFF then some ("Makasar") else none
              else some ("Tolong Siki")
            else if 0x11F5F < v then
              if v < 0x12000 then
                if v < 0x11FC0 then
                  if 0x11FB0 ≤ v ∧ v ≤ 0x11FBF then some ("Lisu Supplement") else none
                else if 0x11FFF < v then
                  none
                else some ("Tamil Supplement")
              else if 0x123FF < v then
                if 0x12400 ≤ v ∧ v ≤ 0x1247F then some ("Cuneiform Numbers and Punctuation") else none
              else some ("Cuneiform")
            else some ("Kawi")
          else some ("Marchen")
        else some ("Warang Citi")
      else some ("Elymaic")
    else if 0x1254F < v then
      if v < 0x1E030 then
        if v < 0x1AFF0 then
          if v < 0x16B00 then
            if v < 0x16100 then
              if v < 0x13430 then
                if v < 0x13000 then
                  if 0x12F90 ≤ v ∧ v ≤ 0x12FFF then some ("Cypro-Minoan") else none
                else if 0x1342F < v then
                  none
                else some ("Egyptian Hieroglyphs")
              else if 0x1345F < v then
                if v < 0x14400 then
                  if 0x13460 ≤ v ∧ v ≤ 0x143FF then some ("Egyptian Hieroglyphs Extended-A") else none
                else if 0x1467F < v then
                  none
                else some ("Anatolian Hieroglyphs")
              else some ("Egyptian Hieroglyph Format Controls")
            else if 0x1613F < v then
              if v < 0x16A70 then
                if v < 0x16A40 then
                  if 0x16800 ≤ v ∧ v ≤ 0x16A3F then some ("Bamum Supplement") else none
                else if 0x16A6F < v then
                  none
                else some ("Mro")
              else if 0x16ACF < v then
                if 0x16AD0 ≤ v ∧ v ≤ 0x16AFF then some ("Bassa Vah") else none
              else some ("Tangsa")
            else some ("Gurung Khema")
          else if 0x16B8F < v then
            if v < 0x17000 then
              if v < 0x16EA0 then
                if v < 0x16E40 then
                  if 0x16D40 ≤ v ∧ v ≤ 0x16D7F then some ("Kirat Rai") else none
                else if 0x16E9F < v then
                  none
                else some ("Medefaidrin")
              else if 0x16EDF < v then
                if v < 0x16FE0 then
                  if 0x16F00 ≤ v ∧ v ≤ 0x16F9F then some ("Miao") else none
                else if 0x16FFF < v then
                  none
                else some ("Ideographic Symbols and Punctuation")
              else some ("Beria Erfe")
            else if 0x187FF < v then
              if v < 0x18D00 then
                if v < 0x18B00 then
                  if 0x18800 ≤ v ∧ v ≤ 0x18AFF then some ("Tangut Components") else none
                else if 0x18CFF < v then
                  none
                else some ("Khitan Small Script")
              else if 0x18D7F < v then
                if 0x18D80 ≤ v ∧ v ≤ 0x18DFF then some ("Tangut Components Supplement") else none
              else some ("Tangut Supplement")
            else some ("Tangut")
          else some ("Pahawh Hmong")
        else if 0x1AFFF < v then
          if v < 0x1D100 then
            if v < 0x1BCA0 then
              if v < 0x1B130 then
                if v < 0x1B100 then
                  if 0x1B000 ≤ v ∧ v ≤ 0x1B0FF then some ("Kana Supplement") else none
                else if 0x1B12F < v then
                  none
                else some ("Kana Extended-A")
              else if 0x1B16F < v then
                if v < 0x1BC00 then
                  if 0x1B170 ≤ v ∧ v ≤ 0x1B2FF then some ("Nushu") else none
                else if 0x1BC9F < v then
                  none
                else some ("Duployan")
              else some ("Small Kana Extension")
            else if 0x1BCAF < v then
              if v < 0x1CF00 then
                if v < 0x1CEC0 then
                  if 0x1CC00 ≤ v ∧ v ≤ 0x1CEBF then some ("Symbols for Legacy Computing Supplement") else none
                else if 0x1CEFF < v then
                  none
                else some ("Miscellaneous Symbols Supplement")
              else if 0x1CFCF < v then
                if 0x1D000 ≤ v ∧ v ≤ 0x1D0FF then some ("Byzantine Musical Symbols") else none
              else some ("Znamenny Musical Notation")
            else some ("Shorthand Format Controls")
          else if 0x1D1FF < v then
            if v < 0x1D360 then
              if v < 0x1D2E0 then
                if v < 0x1D2C0 then
                  if 0x1D200 ≤ v ∧ v ≤ 0x1D24F then some ("Ancient Greek Musical Notation") else none
                else if 0x1D2DF < v then
                  none
                else some ("Kaktovik Numerals")
              else if 0x1D2FF < v then
                if 0x1D300 ≤ v ∧ v ≤ 0x1D35F then some ("Tai Xuan Jing Symbols") else none
              else some ("Mayan Numerals")
            else if 0x1D37F < v then
              if v < 0x1DF00 then
                if v < 0x1D800 then
                  if 0x1D400 ≤ v ∧ v ≤ 0x1D7FF then some ("Mathematical Alphanumeric Symbols") else none
                else if 0x1DAAF < v then
                  none
                else some ("Sutton SignWriting")
              else if 0x1DFFF < v then
                if 0x1E000 ≤ v ∧ v ≤ 0x1E02F then some ("Glagolitic Supplement") else none
              else some ("Latin Extended-G")
            else some ("Counting Rod Numerals")
          else some ("Musical Symbols")
        else some ("Kana Extended-B")
      else if 0x1E08F < v then
        if v < 0x1F700 then
          if v < 0x1ED00 then
            if v < 0x1E6C0 then
              if v < 0x1E2C0 then
                if v < 0x1E290 then
                  if 0x1E100 ≤ v ∧ v ≤ 0x1E14F then some ("Nyiakeng Puachue Hmong") else none
                else if 0x1E2BF < v then
                  none
                else some ("Toto")
              else if 0x1E2FF < v then
                if v < 0x1E5D0 then
                  if 0x1E4D0 ≤ v ∧ v ≤ 0x1E4FF then some ("Nag Mundari") else none
                else if 0x1E5FF < v then
                  none
                else some ("Ol Onal")
              else some ("Wancho")
            else if 0x1E6FF < v then
              if v < 0x1E900 then
                if v < 0x1E800 then
                  if 0x1E7E0 ≤ v ∧ v ≤ 0x1E7FF then some ("Ethiopic Extended-B") else none
                else if 0x1E8DF < v then
                  none
                else some ("Mende Kikakui")
              else if 0x1E95F < v then
                if 0x1EC70 ≤ v ∧ v ≤ 0x1ECBF then some ("Indic Siyaq Numbers") else none
              else some ("Adlam")
            else some ("Tai Yo")
          else if 0x1ED4F < v then
            if v < 0x1F200 then
              if v < 0x1F030 then
                if v < 0x1F000 then
                  if 0x1EE00 ≤ v ∧ v ≤ 0x1EEFF then some ("Arabic Mathematical Alphabetic Symbols") else none
                else if 0x1F02F < v then
                  none
                else some ("Mahjong Tiles")
              else if 0x1F09F < v then
                if v < 0x1F100 then
                  if 0x1F0A0 ≤ v ∧ v ≤ 0x1F0FF then some ("Playing Cards") else none
                else if 0x1F1FF < v then
                  none
                else some ("Enclosed Alphanumeric Supplement")
              else some ("Domino Tiles")
            else if 0x1F2FF < v then
              if v < 0x1F650 then
                if v < 0x1F600 then
                  if 0x1F300 ≤ v ∧ v ≤ 0x1F5FF then some ("Miscellaneous Symbols and Pictographs") else none
                else if 0x1F64F < v then
                  none
                else some ("Emoticons")
              else if 0x1F67F < v then
                if 0x1F680 ≤ v ∧ v ≤ 0x1F6FF then some ("Transport and Map Symbols") else none
              else some ("Ornamental Dingbats")
            else some ("Enclosed Ideographic Supplement")
          else some ("Ottoman Siyaq Numbers")
        else if 0x1F77F < v then
          if v < 0x2CEB0 then
            if v < 0x1FB00 then
              if v < 0x1F900 then
                if v < 0x1F800 then
                  if 0x1F780 ≤ v ∧ v ≤ 0x1F7FF then some ("Geometric Shapes Extended") else none
                else if 0x1F8FF < v then
                  none
                else some ("Supplemental Arrows-C")
              else if 0x1F9FF < v then
                if v < 0x1FA70 then
                  if 0x1FA00 ≤ v ∧ v ≤ 0x1FA6F then some ("Chess Symbols") else none
                else if 0x1FAFF < v then
                  none
                else some ("Symbols and Pictographs Extended-A")
              else some ("Supplemental Symbols and Pictographs")
            else if 0x1FBFF < v then
              if v < 0x2B740 then
                if v < 0x2A700 then
                  if 0x20000 ≤ v ∧ v ≤ 0x2A6DF then some ("CJK Unified Ideographs Extension B") else none
                else if 0x2B73F < v then
                  none
                else some ("CJK Unified Ideographs Extension C")
              else if 0x2B81F < v then
                if 0x2B820 ≤ v ∧ v ≤ 0x2CEAF then some ("CJK Unified Ideographs Extension E") else none
              else some ("CJK Unified Ideographs Extension D")
            else some ("Symbols for Legacy Computing")
          else if 0x2EBEF < v then
            if v < 0x323B0 then
              if v < 0x30000 then
                if v < 0x2F800 then
                  if 0x2EBF0 ≤ v ∧ v ≤ 0x2EE5F then some ("CJK Unified Ideographs Extension I") else none
                else if 0x2FA1F < v then
                  none
                else some ("CJK Compatibility Ideographs Supplement")
              else if 0x3134F < v then
                if 0x31350 ≤ v ∧ v ≤ 0x323AF then some ("CJK Unified Ideographs Extension H") else none
              else some ("CJK Unified Ideographs Extension G")
            else if 0x3347F < v then
              if v < 0xF0000 then
                if v < 0xE0100 then
                  if 0xE0000 ≤ v ∧ v ≤ 0xE007F then some ("Tags") else none
                else if 0xE01EF < v then
                  none
                else some ("Variation Selectors Supplement")
              else if 0xFFFFF < v then
                if 0x100000 ≤ v ∧ v ≤ 0x10FFFF then some ("Supplementary Private Use Area-B") else none
              else some ("Supplementary Private Use Area-A")
            else some ("CJK Unified Ideographs Extension J")
          else some ("CJK Unified Ideographs Extension F")
        else some ("Alchemical Symbols")
      else some ("Cyrillic Extended-D")
    else some ("Early Dynastic Cuneiform")
  else some ("Old Italic")

end Unicode.TableLookupTables.BlockName
