/- This file is generated by table-generators/makeTablesForLookup. -/
module
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Unicode.TableLookupTables.Dash
private def table0 : Array (UInt32 × UInt32) := #[
  ((0x002D : UInt32), (0x002D : UInt32)),
  ((0x058A : UInt32), (0x058A : UInt32)),
  ((0x05BE : UInt32), (0x05BE : UInt32)),
  ((0x1400 : UInt32), (0x1400 : UInt32)),
  ((0x1806 : UInt32), (0x1806 : UInt32)),
  ((0x2010 : UInt32), (0x2015 : UInt32)),
  ((0x2053 : UInt32), (0x2053 : UInt32)),
  ((0x207B : UInt32), (0x207B : UInt32)),
  ((0x208B : UInt32), (0x208B : UInt32)),
  ((0x2212 : UInt32), (0x2212 : UInt32)),
  ((0x2E17 : UInt32), (0x2E17 : UInt32)),
  ((0x2E1A : UInt32), (0x2E1A : UInt32)),
  ((0x2E3A : UInt32), (0x2E3B : UInt32)),
  ((0x2E40 : UInt32), (0x2E40 : UInt32)),
  ((0x2E5D : UInt32), (0x2E5D : UInt32)),
  ((0x301C : UInt32), (0x301C : UInt32)),
  ((0x3030 : UInt32), (0x3030 : UInt32)),
  ((0x30A0 : UInt32), (0x30A0 : UInt32)),
  ((0xFE31 : UInt32), (0xFE32 : UInt32)),
  ((0xFE58 : UInt32), (0xFE58 : UInt32)),
  ((0xFE63 : UInt32), (0xFE63 : UInt32)),
  ((0xFF0D : UInt32), (0xFF0D : UInt32)),
  ((0x10D6E : UInt32), (0x10D6E : UInt32)),
  ((0x10EAD : UInt32), (0x10EAD : UInt32))
]

public def table : Array (UInt32 × UInt32) := Id.run do
  let mut t := #[]
  t := t ++ table0
  return t

end Unicode.TableLookupTables.Dash
