/- This file is generated by table-generators/makeTablesForLookupInLeanFromTablesTxt. -/
module
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Unicode.TableLookupTables.DefaultIgnorableCodePoint
private def table0 : Array (UInt32 × UInt32) := #[
  ((0x00AD : UInt32), (0x00AD : UInt32)),
  ((0x034F : UInt32), (0x034F : UInt32)),
  ((0x061C : UInt32), (0x061C : UInt32)),
  ((0x115F : UInt32), (0x1160 : UInt32)),
  ((0x17B4 : UInt32), (0x17B5 : UInt32)),
  ((0x180B : UInt32), (0x180F : UInt32)),
  ((0x200B : UInt32), (0x200F : UInt32)),
  ((0x202A : UInt32), (0x202E : UInt32)),
  ((0x2060 : UInt32), (0x206F : UInt32)),
  ((0x3164 : UInt32), (0x3164 : UInt32)),
  ((0xFE00 : UInt32), (0xFE0F : UInt32)),
  ((0xFEFF : UInt32), (0xFEFF : UInt32)),
  ((0xFFA0 : UInt32), (0xFFA0 : UInt32)),
  ((0xFFF0 : UInt32), (0xFFF8 : UInt32)),
  ((0x1BCA0 : UInt32), (0x1BCA3 : UInt32)),
  ((0x1D173 : UInt32), (0x1D17A : UInt32)),
  ((0xE0000 : UInt32), (0xE0FFF : UInt32))
]

public def table : Array (UInt32 × UInt32) := Id.run do
  let mut t := #[]
  t := t ++ table0
  return t

end Unicode.TableLookupTables.DefaultIgnorableCodePoint
