/- This file is generated by table-generators/makeTablesForLookup. -/
module
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Unicode.TableLookupTables.EmojiModifier
private def table0 : Array (UInt32 × UInt32) := #[
  ((0x1F3FB : UInt32), (0x1F3FF : UInt32))
]

public def table : Array (UInt32 × UInt32) := Id.run do
  let mut t := #[]
  t := t ++ table0
  return t

end Unicode.TableLookupTables.EmojiModifier
