/- This file is generated by table-generators/makeTablesForLookupInLeanFromTablesTxt. -/
module
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Unicode.TableLookupTables.EmojiModifierBase
private def table0 : Array (UInt32 × UInt32) := #[
  ((0x261D : UInt32), (0x261D : UInt32)),
  ((0x26F9 : UInt32), (0x26F9 : UInt32)),
  ((0x270A : UInt32), (0x270C : UInt32)),
  ((0x270D : UInt32), (0x270D : UInt32)),
  ((0x1F385 : UInt32), (0x1F385 : UInt32)),
  ((0x1F3C2 : UInt32), (0x1F3C4 : UInt32)),
  ((0x1F3C7 : UInt32), (0x1F3C7 : UInt32)),
  ((0x1F3CA : UInt32), (0x1F3CA : UInt32)),
  ((0x1F3CB : UInt32), (0x1F3CC : UInt32)),
  ((0x1F442 : UInt32), (0x1F443 : UInt32)),
  ((0x1F446 : UInt32), (0x1F450 : UInt32)),
  ((0x1F466 : UInt32), (0x1F46B : UInt32)),
  ((0x1F46C : UInt32), (0x1F46D : UInt32)),
  ((0x1F46E : UInt32), (0x1F478 : UInt32)),
  ((0x1F47C : UInt32), (0x1F47C : UInt32)),
  ((0x1F481 : UInt32), (0x1F483 : UInt32)),
  ((0x1F485 : UInt32), (0x1F487 : UInt32)),
  ((0x1F48F : UInt32), (0x1F48F : UInt32)),
  ((0x1F491 : UInt32), (0x1F491 : UInt32)),
  ((0x1F4AA : UInt32), (0x1F4AA : UInt32)),
  ((0x1F574 : UInt32), (0x1F575 : UInt32)),
  ((0x1F57A : UInt32), (0x1F57A : UInt32)),
  ((0x1F590 : UInt32), (0x1F590 : UInt32)),
  ((0x1F595 : UInt32), (0x1F596 : UInt32)),
  ((0x1F645 : UInt32), (0x1F647 : UInt32)),
  ((0x1F64B : UInt32), (0x1F64F : UInt32)),
  ((0x1F6A3 : UInt32), (0x1F6A3 : UInt32)),
  ((0x1F6B4 : UInt32), (0x1F6B5 : UInt32)),
  ((0x1F6B6 : UInt32), (0x1F6B6 : UInt32)),
  ((0x1F6C0 : UInt32), (0x1F6C0 : UInt32)),
  ((0x1F6CC : UInt32), (0x1F6CC : UInt32)),
  ((0x1F90C : UInt32), (0x1F90C : UInt32)),
  ((0x1F90F : UInt32), (0x1F90F : UInt32)),
  ((0x1F918 : UInt32), (0x1F918 : UInt32)),
  ((0x1F919 : UInt32), (0x1F91E : UInt32)),
  ((0x1F91F : UInt32), (0x1F91F : UInt32)),
  ((0x1F926 : UInt32), (0x1F926 : UInt32)),
  ((0x1F930 : UInt32), (0x1F930 : UInt32)),
  ((0x1F931 : UInt32), (0x1F932 : UInt32)),
  ((0x1F933 : UInt32), (0x1F939 : UInt32)),
  ((0x1F93C : UInt32), (0x1F93E : UInt32)),
  ((0x1F977 : UInt32), (0x1F977 : UInt32)),
  ((0x1F9B5 : UInt32), (0x1F9B6 : UInt32)),
  ((0x1F9B8 : UInt32), (0x1F9B9 : UInt32)),
  ((0x1F9BB : UInt32), (0x1F9BB : UInt32)),
  ((0x1F9CD : UInt32), (0x1F9CF : UInt32)),
  ((0x1F9D1 : UInt32), (0x1F9DD : UInt32)),
  ((0x1FAC3 : UInt32), (0x1FAC5 : UInt32)),
  ((0x1FAF0 : UInt32), (0x1FAF6 : UInt32)),
  ((0x1FAF7 : UInt32), (0x1FAF8 : UInt32))
]

public def table : Array (UInt32 × UInt32) := Id.run do
  let mut t := #[]
  t := t ++ table0
  return t

end Unicode.TableLookupTables.EmojiModifierBase
