/- This file is generated by table-generators/makeTablesForLookup. -/
module
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Unicode.TableLookupTables.EmojiComponent
private def table0 : Array (UInt32 × UInt32) := #[
  ((0x0023 : UInt32), (0x0023 : UInt32)),
  ((0x002A : UInt32), (0x002A : UInt32)),
  ((0x0030 : UInt32), (0x0039 : UInt32)),
  ((0x200D : UInt32), (0x200D : UInt32)),
  ((0x20E3 : UInt32), (0x20E3 : UInt32)),
  ((0xFE0F : UInt32), (0xFE0F : UInt32)),
  ((0x1F1E6 : UInt32), (0x1F1FF : UInt32)),
  ((0x1F3FB : UInt32), (0x1F3FF : UInt32)),
  ((0x1F9B0 : UInt32), (0x1F9B3 : UInt32)),
  ((0xE0020 : UInt32), (0xE007F : UInt32))
]

public def table : Array (UInt32 × UInt32) := Id.run do
  let mut t := #[]
  t := t ++ table0
  return t

end Unicode.TableLookupTables.EmojiComponent
