/- This file is generated by table-generators/makeTablesForLookupInLeanFromTablesTxt. -/
module
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Unicode.TableLookupTables.Extender
private def table0 : Array (UInt32 × UInt32) := #[
  ((0x00B7 : UInt32), (0x00B7 : UInt32)),
  ((0x02D0 : UInt32), (0x02D1 : UInt32)),
  ((0x0640 : UInt32), (0x0640 : UInt32)),
  ((0x07FA : UInt32), (0x07FA : UInt32)),
  ((0x0A71 : UInt32), (0x0A71 : UInt32)),
  ((0x0AFB : UInt32), (0x0AFB : UInt32)),
  ((0x0B55 : UInt32), (0x0B55 : UInt32)),
  ((0x0E46 : UInt32), (0x0E46 : UInt32)),
  ((0x0EC6 : UInt32), (0x0EC6 : UInt32)),
  ((0x180A : UInt32), (0x180A : UInt32)),
  ((0x1843 : UInt32), (0x1843 : UInt32)),
  ((0x1AA7 : UInt32), (0x1AA7 : UInt32)),
  ((0x1C36 : UInt32), (0x1C36 : UInt32)),
  ((0x1C7B : UInt32), (0x1C7B : UInt32)),
  ((0x3005 : UInt32), (0x3005 : UInt32)),
  ((0x3031 : UInt32), (0x3035 : UInt32)),
  ((0x309D : UInt32), (0x309E : UInt32)),
  ((0x30FC : UInt32), (0x30FE : UInt32)),
  ((0xA015 : UInt32), (0xA015 : UInt32)),
  ((0xA60C : UInt32), (0xA60C : UInt32)),
  ((0xA9CF : UInt32), (0xA9CF : UInt32)),
  ((0xA9E6 : UInt32), (0xA9E6 : UInt32)),
  ((0xAA70 : UInt32), (0xAA70 : UInt32)),
  ((0xAADD : UInt32), (0xAADD : UInt32)),
  ((0xAAF3 : UInt32), (0xAAF4 : UInt32)),
  ((0xFF70 : UInt32), (0xFF70 : UInt32)),
  ((0x10781 : UInt32), (0x10782 : UInt32)),
  ((0x10D4E : UInt32), (0x10D4E : UInt32)),
  ((0x10D6A : UInt32), (0x10D6A : UInt32)),
  ((0x10D6F : UInt32), (0x10D6F : UInt32)),
  ((0x11237 : UInt32), (0x11237 : UInt32)),
  ((0x1135D : UInt32), (0x1135D : UInt32)),
  ((0x113D2 : UInt32), (0x113D2 : UInt32)),
  ((0x113D3 : UInt32), (0x113D3 : UInt32)),
  ((0x115C6 : UInt32), (0x115C8 : UInt32)),
  ((0x11A98 : UInt32), (0x11A98 : UInt32)),
  ((0x11DD9 : UInt32), (0x11DD9 : UInt32)),
  ((0x16B42 : UInt32), (0x16B43 : UInt32)),
  ((0x16FE0 : UInt32), (0x16FE1 : UInt32)),
  ((0x16FE3 : UInt32), (0x16FE3 : UInt32)),
  ((0x16FF2 : UInt32), (0x16FF3 : UInt32)),
  ((0x1E13C : UInt32), (0x1E13D : UInt32)),
  ((0x1E5EF : UInt32), (0x1E5EF : UInt32)),
  ((0x1E944 : UInt32), (0x1E946 : UInt32))
]

public def table : Array (UInt32 × UInt32) := Id.run do
  let mut t := #[]
  t := t ++ table0
  return t

end Unicode.TableLookupTables.Extender
