/- This file is generated by table-generators/makeTablesForLookup. -/
module
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Unicode.TableLookupTables.Hyphen
private def table0 : Array (UInt32 × UInt32) := #[
  ((0x002D : UInt32), (0x002D : UInt32)),
  ((0x00AD : UInt32), (0x00AD : UInt32)),
  ((0x058A : UInt32), (0x058A : UInt32)),
  ((0x1806 : UInt32), (0x1806 : UInt32)),
  ((0x2010 : UInt32), (0x2011 : UInt32)),
  ((0x2E17 : UInt32), (0x2E17 : UInt32)),
  ((0x30FB : UInt32), (0x30FB : UInt32)),
  ((0xFE63 : UInt32), (0xFE63 : UInt32)),
  ((0xFF0D : UInt32), (0xFF0D : UInt32)),
  ((0xFF65 : UInt32), (0xFF65 : UInt32))
]

public def table : Array (UInt32 × UInt32) := Id.run do
  let mut t := #[]
  t := t ++ table0
  return t

end Unicode.TableLookupTables.Hyphen
