/- This file is generated by table-generators/makeTablesForLookup. -/
module
public import UnicodeBasic.TableLookupTables.Name.Chunk0
public import UnicodeBasic.TableLookupTables.Name.Chunk1
public import UnicodeBasic.TableLookupTables.Name.Chunk2
public import UnicodeBasic.TableLookupTables.Name.Chunk3
public import UnicodeBasic.TableLookupTables.Name.Chunk4
public import UnicodeBasic.TableLookupTables.Name.Chunk5
public import UnicodeBasic.TableLookupTables.Name.Chunk6
public import UnicodeBasic.TableLookupTables.Name.Chunk7
public import UnicodeBasic.TableLookupTables.Name.Chunk8
public import UnicodeBasic.TableLookupTables.Name.Chunk9
public import UnicodeBasic.TableLookupTables.Name.Chunk10
public import UnicodeBasic.TableLookupTables.Name.Chunk11
public import UnicodeBasic.TableLookupTables.Name.Chunk12
public import UnicodeBasic.TableLookupTables.Name.Chunk13
public import UnicodeBasic.TableLookupTables.Name.Chunk14
public import UnicodeBasic.TableLookupTables.Name.Chunk15
public import UnicodeBasic.TableLookupTables.Name.Chunk16
public import UnicodeBasic.TableLookupTables.Name.Chunk17
public import UnicodeBasic.TableLookupTables.Name.Chunk18
public import UnicodeBasic.TableLookupTables.Name.Chunk19
public import UnicodeBasic.TableLookupTables.Name.Chunk20
public import UnicodeBasic.TableLookupTables.Name.Chunk21
public import UnicodeBasic.TableLookupTables.Name.Chunk22
public import UnicodeBasic.TableLookupTables.Name.Chunk23
public import UnicodeBasic.TableLookupTables.Name.Chunk24
public import UnicodeBasic.TableLookupTables.Name.Chunk25
public import UnicodeBasic.TableLookupTables.Name.Chunk26
public import UnicodeBasic.TableLookupTables.Name.Chunk27
public import UnicodeBasic.TableLookupTables.Name.Chunk28
public import UnicodeBasic.TableLookupTables.Name.Chunk29
public import UnicodeBasic.TableLookupTables.Name.Chunk30
public import UnicodeBasic.TableLookupTables.Name.Chunk31
public import UnicodeBasic.TableLookupTables.Name.Chunk32
public import UnicodeBasic.TableLookupTables.Name.Chunk33
public import UnicodeBasic.TableLookupTables.Name.Chunk34
public import UnicodeBasic.TableLookupTables.Name.Chunk35
public import UnicodeBasic.TableLookupTables.Name.Chunk36
public import UnicodeBasic.TableLookupTables.Name.Chunk37
public import UnicodeBasic.TableLookupTables.Name.Chunk38
public import UnicodeBasic.TableLookupTables.Name.Chunk39
public import UnicodeBasic.TableLookupTables.Name.Chunk40
public import UnicodeBasic.TableLookupTables.Name.Chunk41
public import UnicodeBasic.TableLookupTables.Name.Chunk42
public import UnicodeBasic.TableLookupTables.Name.Chunk43
public import UnicodeBasic.TableLookupTables.Name.Chunk44
public import UnicodeBasic.TableLookupTables.Name.Chunk45
public import UnicodeBasic.TableLookupTables.Name.Chunk46
public import UnicodeBasic.TableLookupTables.Name.Chunk47
public import UnicodeBasic.TableLookupTables.Name.Chunk48
public import UnicodeBasic.TableLookupTables.Name.Chunk49
public import UnicodeBasic.TableLookupTables.Name.Chunk50
public import UnicodeBasic.TableLookupTables.Name.Chunk51
public import UnicodeBasic.TableLookupTables.Name.Chunk52
public import UnicodeBasic.TableLookupTables.Name.Chunk53
public import UnicodeBasic.TableLookupTables.Name.Chunk54
public import UnicodeBasic.TableLookupTables.Name.Chunk55
public import UnicodeBasic.TableLookupTables.Name.Chunk56
public import UnicodeBasic.TableLookupTables.Name.Chunk57
public import UnicodeBasic.TableLookupTables.Name.Chunk58
public import UnicodeBasic.TableLookupTables.Name.Chunk59
public import UnicodeBasic.TableLookupTables.Name.Chunk60
public import UnicodeBasic.TableLookupTables.Name.Chunk61
public import UnicodeBasic.TableLookupTables.Name.Chunk62
public import UnicodeBasic.TableLookupTables.Name.Chunk63
public import UnicodeBasic.TableLookupTables.Name.Chunk64
public import UnicodeBasic.TableLookupTables.Name.Chunk65
public import UnicodeBasic.TableLookupTables.Name.Chunk66
public import UnicodeBasic.TableLookupTables.Name.Chunk67
public import UnicodeBasic.TableLookupTables.Name.Chunk68
public import UnicodeBasic.TableLookupTables.Name.Chunk69
public import UnicodeBasic.TableLookupTables.Name.Chunk70
public import UnicodeBasic.TableLookupTables.Name.Chunk71
public import UnicodeBasic.TableLookupTables.Name.Chunk72
public import UnicodeBasic.TableLookupTables.Name.Chunk73

namespace Unicode.TableLookupTables.Name

public def table : Array (UInt32 × UInt32 × String) := Id.run do
  let mut t := #[]
  t := t ++ Chunk0.table
  t := t ++ Chunk1.table
  t := t ++ Chunk2.table
  t := t ++ Chunk3.table
  t := t ++ Chunk4.table
  t := t ++ Chunk5.table
  t := t ++ Chunk6.table
  t := t ++ Chunk7.table
  t := t ++ Chunk8.table
  t := t ++ Chunk9.table
  t := t ++ Chunk10.table
  t := t ++ Chunk11.table
  t := t ++ Chunk12.table
  t := t ++ Chunk13.table
  t := t ++ Chunk14.table
  t := t ++ Chunk15.table
  t := t ++ Chunk16.table
  t := t ++ Chunk17.table
  t := t ++ Chunk18.table
  t := t ++ Chunk19.table
  t := t ++ Chunk20.table
  t := t ++ Chunk21.table
  t := t ++ Chunk22.table
  t := t ++ Chunk23.table
  t := t ++ Chunk24.table
  t := t ++ Chunk25.table
  t := t ++ Chunk26.table
  t := t ++ Chunk27.table
  t := t ++ Chunk28.table
  t := t ++ Chunk29.table
  t := t ++ Chunk30.table
  t := t ++ Chunk31.table
  t := t ++ Chunk32.table
  t := t ++ Chunk33.table
  t := t ++ Chunk34.table
  t := t ++ Chunk35.table
  t := t ++ Chunk36.table
  t := t ++ Chunk37.table
  t := t ++ Chunk38.table
  t := t ++ Chunk39.table
  t := t ++ Chunk40.table
  t := t ++ Chunk41.table
  t := t ++ Chunk42.table
  t := t ++ Chunk43.table
  t := t ++ Chunk44.table
  t := t ++ Chunk45.table
  t := t ++ Chunk46.table
  t := t ++ Chunk47.table
  t := t ++ Chunk48.table
  t := t ++ Chunk49.table
  t := t ++ Chunk50.table
  t := t ++ Chunk51.table
  t := t ++ Chunk52.table
  t := t ++ Chunk53.table
  t := t ++ Chunk54.table
  t := t ++ Chunk55.table
  t := t ++ Chunk56.table
  t := t ++ Chunk57.table
  t := t ++ Chunk58.table
  t := t ++ Chunk59.table
  t := t ++ Chunk60.table
  t := t ++ Chunk61.table
  t := t ++ Chunk62.table
  t := t ++ Chunk63.table
  t := t ++ Chunk64.table
  t := t ++ Chunk65.table
  t := t ++ Chunk66.table
  t := t ++ Chunk67.table
  t := t ++ Chunk68.table
  t := t ++ Chunk69.table
  t := t ++ Chunk70.table
  t := t ++ Chunk71.table
  t := t ++ Chunk72.table
  t := t ++ Chunk73.table
  return t

end Unicode.TableLookupTables.Name
