/- This file is generated by table-generators/makeTablesForLookup. -/
module
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Unicode.TableLookupTables.OtherLowercase
private def table0 : Array (UInt32 × UInt32) := #[
  ((0x00AA : UInt32), (0x00AA : UInt32)),
  ((0x00BA : UInt32), (0x00BA : UInt32)),
  ((0x02B0 : UInt32), (0x02B8 : UInt32)),
  ((0x02C0 : UInt32), (0x02C1 : UInt32)),
  ((0x02E0 : UInt32), (0x02E4 : UInt32)),
  ((0x0345 : UInt32), (0x0345 : UInt32)),
  ((0x037A : UInt32), (0x037A : UInt32)),
  ((0x10FC : UInt32), (0x10FC : UInt32)),
  ((0x1D2C : UInt32), (0x1D6A : UInt32)),
  ((0x1D78 : UInt32), (0x1D78 : UInt32)),
  ((0x1D9B : UInt32), (0x1DBF : UInt32)),
  ((0x2071 : UInt32), (0x2071 : UInt32)),
  ((0x207F : UInt32), (0x207F : UInt32)),
  ((0x2090 : UInt32), (0x209C : UInt32)),
  ((0x2170 : UInt32), (0x217F : UInt32)),
  ((0x24D0 : UInt32), (0x24E9 : UInt32)),
  ((0x2C7C : UInt32), (0x2C7D : UInt32)),
  ((0xA69C : UInt32), (0xA69D : UInt32)),
  ((0xA770 : UInt32), (0xA770 : UInt32)),
  ((0xA7F1 : UInt32), (0xA7F4 : UInt32)),
  ((0xA7F8 : UInt32), (0xA7F9 : UInt32)),
  ((0xAB5C : UInt32), (0xAB5F : UInt32)),
  ((0xAB69 : UInt32), (0xAB69 : UInt32)),
  ((0x10780 : UInt32), (0x10780 : UInt32)),
  ((0x10783 : UInt32), (0x10785 : UInt32)),
  ((0x10787 : UInt32), (0x107B0 : UInt32)),
  ((0x107B2 : UInt32), (0x107BA : UInt32)),
  ((0x1E030 : UInt32), (0x1E06D : UInt32))
]

public def table : Array (UInt32 × UInt32) := Id.run do
  let mut t := #[]
  t := t ++ table0
  return t

end Unicode.TableLookupTables.OtherLowercase
