/- This file is generated by table-generators/makeTablesForLookup. -/
module
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Unicode.TableLookupTables.OtherUppercase
private def table0 : Array (UInt32 × UInt32) := #[
  ((0x2160 : UInt32), (0x216F : UInt32)),
  ((0x24B6 : UInt32), (0x24CF : UInt32)),
  ((0x1F130 : UInt32), (0x1F149 : UInt32)),
  ((0x1F150 : UInt32), (0x1F169 : UInt32)),
  ((0x1F170 : UInt32), (0x1F189 : UInt32))
]

public def table : Array (UInt32 × UInt32) := Id.run do
  let mut t := #[]
  t := t ++ table0
  return t

end Unicode.TableLookupTables.OtherUppercase
