/- This file is generated by table-generators/makeTablesForLookupInLeanFromTablesTxt. -/
module
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Unicode.TableLookupTables.QuotationMark
private def table0 : Array (UInt32 × UInt32) := #[
  ((0x0022 : UInt32), (0x0022 : UInt32)),
  ((0x0027 : UInt32), (0x0027 : UInt32)),
  ((0x00AB : UInt32), (0x00AB : UInt32)),
  ((0x00BB : UInt32), (0x00BB : UInt32)),
  ((0x2018 : UInt32), (0x2018 : UInt32)),
  ((0x2019 : UInt32), (0x2019 : UInt32)),
  ((0x201A : UInt32), (0x201A : UInt32)),
  ((0x201B : UInt32), (0x201C : UInt32)),
  ((0x201D : UInt32), (0x201D : UInt32)),
  ((0x201E : UInt32), (0x201E : UInt32)),
  ((0x201F : UInt32), (0x201F : UInt32)),
  ((0x2039 : UInt32), (0x2039 : UInt32)),
  ((0x203A : UInt32), (0x203A : UInt32)),
  ((0x2E42 : UInt32), (0x2E42 : UInt32)),
  ((0x300C : UInt32), (0x300C : UInt32)),
  ((0x300D : UInt32), (0x300D : UInt32)),
  ((0x300E : UInt32), (0x300E : UInt32)),
  ((0x300F : UInt32), (0x300F : UInt32)),
  ((0x301D : UInt32), (0x301D : UInt32)),
  ((0x301E : UInt32), (0x301F : UInt32)),
  ((0xFE41 : UInt32), (0xFE41 : UInt32)),
  ((0xFE42 : UInt32), (0xFE42 : UInt32)),
  ((0xFE43 : UInt32), (0xFE43 : UInt32)),
  ((0xFE44 : UInt32), (0xFE44 : UInt32)),
  ((0xFF02 : UInt32), (0xFF02 : UInt32)),
  ((0xFF07 : UInt32), (0xFF07 : UInt32)),
  ((0xFF62 : UInt32), (0xFF62 : UInt32)),
  ((0xFF63 : UInt32), (0xFF63 : UInt32))
]

public def table : Array (UInt32 × UInt32) := Id.run do
  let mut t := #[]
  t := t ++ table0
  return t

end Unicode.TableLookupTables.QuotationMark
