/- This file is generated by table-generators/makeTablesForLookupInLeanFromTablesTxt. -/
module
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Unicode.TableLookupTables.RegionalIndicator
private def table0 : Array (UInt32 × UInt32) := #[
  ((0x1F1E6 : UInt32), (0x1F1FF : UInt32))
]

public def table : Array (UInt32 × UInt32) := Id.run do
  let mut t := #[]
  t := t ++ table0
  return t

end Unicode.TableLookupTables.RegionalIndicator
