/- This file is generated by table-generators/makeTablesForLookup. -/
module

@[expose] public section

namespace Unicode.TableLookupTables.ScriptExtensions

abbrev start : UInt32 := 0x00B7

abbrev «end» : UInt32 := 0x1F250

abbrev BetweenOrEqStartEnd (v : UInt32) : Prop := start ≤ v ∧ v ≤ «end»

@[inline_if_reduce, reducible]
def lookupSparseKVTable? (c : UInt32) (_h : BetweenOrEqStartEnd c) : Option String :=
  if c < 0x1CEB then
    if c < 0x061B then
      if c < 0x0310 then
        if c < 0x0304 then
          if c < 0x02D7 then
            if c < 0x02C7 then
              if c < 0x02BC then
                if c == 0x00B7 then some ("00B7;Avst Cari Copt Dupl Elba Geor Glag Gong Goth Grek Hani Latn Lydi Mahj Perm Shaw") else none
              else if c == 0x02BC then some ("02BC;Beng Cyrl Deva Latn Lisu Thai Toto")
              else
                none
            else if c == 0x02C7 then some ("02C7;Bopo Latn")
            else
              if c < 0x02CD then
                if c == 0x02C9 then some ("02CB;Bopo Latn") else none
              else if c == 0x02CD then some ("02CD;Latn Lisu")
              else
                none
          else if c == 0x02D7 then some ("02D7;Latn Thai")
          else
            if c < 0x0301 then
              if c < 0x0300 then
                if c == 0x02D9 then some ("02D9;Bopo Latn") else none
              else if c == 0x0300 then some ("0300;Cher Copt Cyrl Grek Latn Perm Sunu Tale")
              else
                none
            else if c == 0x0301 then some ("0301;Cher Cyrl Grek Latn Osge Sunu Tale Todr")
            else
              if c < 0x0303 then
                if c == 0x0302 then some ("0302;Cher Cyrl Latn Tfng") else none
              else if c == 0x0303 then some ("0303;Glag Latn Sunu Syrc Thai")
              else
                none
        else if c == 0x0304 then some ("0304;Aghb Cher Copt Cyrl Goth Grek Latn Osge Syrc Tfng Todr")
        else
          if c < 0x030A then
            if c < 0x0307 then
              if c < 0x0306 then
                if c == 0x0305 then some ("0305;Copt Elba Glag Goth Kana Latn") else none
              else if c == 0x0306 then some ("0306;Cyrl Grek Latn Perm Tfng")
              else
                none
            else if c == 0x0307 then some ("0307;Copt Dupl Hebr Latn Perm Syrc Tale Tfng Todr")
            else
              if c < 0x0309 then
                if c == 0x0308 then some ("0308;Armn Cyrl Dupl Goth Grek Hebr Latn Perm Syrc Tale Tfng") else none
              else if c == 0x0309 then some ("0309;Latn Tfng")
              else
                none
          else if c == 0x030A then some ("030A;Dupl Latn Syrc")
          else
            if c < 0x030D then
              if c < 0x030C then
                if c == 0x030B then some ("030B;Cher Cyrl Latn Osge") else none
              else if c == 0x030C then some ("030C;Cher Latn Tale")
              else
                none
            else if c == 0x030D then some ("030D;Latn Sunu")
            else
              if c == 0x030E then some ("030E;Ethi Latn") else none
      else if c == 0x0310 then some ("0310;Latn Sunu")
      else
        if c < 0x0345 then
          if c < 0x032D then
            if c < 0x0323 then
              if c < 0x0313 then
                if c == 0x0311 then some ("0311;Cyrl Latn Todr") else none
              else if c == 0x0313 then some ("0313;Grek Latn Perm Todr")
              else
                none
            else if c == 0x0323 then some ("0323;Cher Dupl Kana Latn Syrc Tfng")
            else
              if c < 0x0325 then
                if c == 0x0324 then some ("0324;Cher Dupl Latn Syrc") else none
              else if c == 0x0325 then some ("0325;Latn Syrc")
              else
                none
          else if c == 0x032D then some ("032D;Latn Sunu Syrc")
          else
            if c < 0x0331 then
              if c < 0x0330 then
                if c == 0x032E then some ("032E;Latn Syrc") else none
              else if c == 0x0330 then some ("0330;Cher Latn Syrc")
              else
                none
            else if c == 0x0331 then some ("0331;Aghb Cher Goth Latn Sunu Syrc Thai")
            else
              if c == 0x0342 then some ("0342;Grek") else none
        else if c == 0x0345 then some ("0345;Grek")
        else
          if c < 0x0484 then
            if c < 0x0363 then
              if c < 0x035E then
                if c == 0x0358 then some ("0358;Latn Osge") else none
              else if c == 0x035E then some ("035E;Aghb Latn Todr")
              else
                none
            else if c == 0x0363 then some ("036F;Latn")
            else
              if c < 0x0483 then
                if c == 0x0374 then some ("0375;Copt Grek") else none
              else if c == 0x0483 then some ("0483;Cyrl Perm")
              else
                none
          else if c == 0x0484 then some ("0484;Cyrl Glag")
          else
            if c < 0x0589 then
              if c < 0x0487 then
                if c == 0x0485 then some ("0486;Cyrl Latn") else none
              else if c == 0x0487 then some ("0487;Cyrl Glag")
              else
                none
            else if c == 0x0589 then some ("0589;Armn Geor Glag")
            else
              if c == 0x060C then some ("060C;Arab Gara Nkoo Rohg Syrc Thaa Yezi") else none
    else if c == 0x061B then some ("061B;Arab Gara Nkoo Rohg Syrc Thaa Yezi")
    else
      if c < 0x1802 then
        if c < 0x0965 then
          if c < 0x0670 then
            if c < 0x0640 then
              if c < 0x061F then
                if c == 0x061C then some ("061C;Arab Syrc Thaa") else none
              else if c == 0x061F then some ("061F;Adlm Arab Gara Nkoo Rohg Syrc Thaa Yezi")
              else
                none
            else if c == 0x0640 then some ("0640;Adlm Arab Mand Mani Ougr Phlp Rohg Sogd Syrc")
            else
              if c < 0x0660 then
                if c == 0x064B then some ("0655;Arab Syrc") else none
              else if c == 0x0660 then some ("0669;Arab Thaa Yezi")
              else
                none
          else if c == 0x0670 then some ("0670;Arab Syrc")
          else
            if c < 0x0952 then
              if c < 0x0951 then
                if c == 0x06D4 then some ("06D4;Arab Rohg") else none
              else if c == 0x0951 then some ("0951;Beng Deva Gran Gujr Guru Knda Latn Mlym Nand Newa Orya Shrd Taml Telu Tirh")
              else
                none
            else if c == 0x0952 then some ("0952;Beng Deva Gran Gujr Guru Knda Latn Mlym Newa Orya Taml Telu Tirh")
            else
              if c == 0x0964 then some ("0964;Beng Deva Dogr Gong Gonm Gran Gujr Guru Knda Mahj Mlym Nand Onao Orya Sind Sinh Sylo Takr Taml Telu Tirh") else none
        else if c == 0x0965 then some ("0965;Beng Deva Dogr Gong Gonm Gran Gujr Gukh Guru Knda Limb Mahj Mlym Nand Onao Orya Sind Sinh Sylo Takr Taml Telu Tirh")
        else
          if c < 0x0CE6 then
            if c < 0x0A66 then
              if c < 0x09E6 then
                if c == 0x0966 then some ("096F;Deva Dogr Kthi Mahj") else none
              else if c == 0x09E6 then some ("09EF;Beng Cakm Sylo")
              else
                none
            else if c == 0x0A66 then some ("0A6F;Guru Mult")
            else
              if c < 0x0BE6 then
                if c == 0x0AE6 then some ("0AEF;Gujr Khoj") else none
              else if c == 0x0BE6 then some ("0BF3;Gran Taml")
              else
                none
          else if c == 0x0CE6 then some ("0CEF;Knda Nand Tutg")
          else
            if c < 0x16EB then
              if c < 0x10FB then
                if c == 0x1040 then some ("1049;Cakm Mymr Tale") else none
              else if c == 0x10FB then some ("10FB;Geor Glag Latn")
              else
                none
            else if c == 0x16EB then some ("16ED;Runr")
            else
              if c == 0x1735 then some ("1736;Buhd Hano Tagb Tglg") else none
      else if c == 0x1802 then some ("1803;Mong Phag")
      else
        if c < 0x1CD9 then
          if c < 0x1CD4 then
            if c < 0x1CD1 then
              if c < 0x1CD0 then
                if c == 0x1805 then some ("1805;Mong Phag") else none
              else if c == 0x1CD0 then some ("1CD0;Beng Deva Gran Knda")
              else
                none
            else if c == 0x1CD1 then some ("1CD1;Deva")
            else
              if c < 0x1CD3 then
                if c == 0x1CD2 then some ("1CD2;Beng Deva Gran Knda") else none
              else if c == 0x1CD3 then some ("1CD3;Deva Gran Knda")
              else
                none
          else if c == 0x1CD4 then some ("1CD4;Deva")
          else
            if c < 0x1CD7 then
              if c < 0x1CD6 then
                if c == 0x1CD5 then some ("1CD5;Beng Deva Newa Telu Tirh") else none
              else if c == 0x1CD6 then some ("1CD6;Beng Deva Telu")
              else
                none
            else if c == 0x1CD7 then some ("1CD7;Deva Newa Shrd")
            else
              if c == 0x1CD8 then some ("1CD8;Beng Deva Newa Telu") else none
        else if c == 0x1CD9 then some ("1CD9;Deva Shrd")
        else
          if c < 0x1CE1 then
            if c < 0x1CDC then
              if c < 0x1CDB then
                if c == 0x1CDA then some ("1CDA;Deva Knda Mlym Orya Taml Telu") else none
              else if c == 0x1CDB then some ("1CDB;Deva")
              else
                none
            else if c == 0x1CDC then some ("1CDD;Deva Shrd")
            else
              if c < 0x1CE0 then
                if c == 0x1CDE then some ("1CDF;Deva") else none
              else if c == 0x1CE0 then some ("1CE0;Deva Shrd")
              else
                none
          else if c == 0x1CE1 then some ("1CE1;Beng Deva")
          else
            if c < 0x1CE9 then
              if c < 0x1CE3 then
                if c == 0x1CE2 then some ("1CE2;Deva Newa Tirh") else none
              else if c == 0x1CE3 then some ("1CE8;Deva")
              else
                none
            else if c == 0x1CE9 then some ("1CE9;Deva Nand Newa")
            else
              if c == 0x1CEA then some ("1CEA;Beng Deva Shrd") else none
  else if c == 0x1CEB then some ("1CEB;Deva Newa")
  else
    if c < 0x30FB then
      if c < 0x2E3C then
        if c < 0x1DC0 then
          if c < 0x1CF4 then
            if c < 0x1CEE then
              if c < 0x1CED then
                if c == 0x1CEC then some ("1CEC;Deva") else none
              else if c == 0x1CED then some ("1CED;Beng Deva Newa Shrd")
              else
                none
            else if c == 0x1CEE then some ("1CF1;Deva")
            else
              if c < 0x1CF3 then
                if c == 0x1CF2 then some ("1CF2;Beng Deva Gran Knda Mlym Nand Orya Sinh Telu Tirh Tutg") else none
              else if c == 0x1CF3 then some ("1CF3;Deva Gran")
              else
                none
          else if c == 0x1CF4 then some ("1CF4;Deva Gran Knda Tutg")
          else
            if c < 0x1CF8 then
              if c < 0x1CF7 then
                if c == 0x1CF5 then some ("1CF6;Beng Deva") else none
              else if c == 0x1CF7 then some ("1CF7;Beng")
              else
                none
            else if c == 0x1CF8 then some ("1CF9;Deva Gran")
            else
              if c == 0x1CFA then some ("1CFA;Nand") else none
        else if c == 0x1DC0 then some ("1DC1;Grek")
        else
          if c < 0x205D then
            if c < 0x202F then
              if c < 0x1DFA then
                if c == 0x1DF8 then some ("1DF8;Cyrl Latn Syrc") else none
              else if c == 0x1DFA then some ("1DFA;Syrc")
              else
                none
            else if c == 0x202F then some ("202F;Latn Mong Phag")
            else
              if c < 0x205A then
                if c == 0x204F then some ("204F;Adlm Arab") else none
              else if c == 0x205A then some ("205A;Cari Geor Glag Hung Lyci Orkh")
              else
                none
          else if c == 0x205D then some ("205D;Cari Grek Hung Mero")
          else
            if c < 0x2E30 then
              if c < 0x2E17 then
                if c == 0x20F0 then some ("20F0;Deva Gran Latn") else none
              else if c == 0x2E17 then some ("2E17;Copt Latn")
              else
                none
            else if c == 0x2E30 then some ("2E30;Avst Orkh")
            else
              if c == 0x2E31 then some ("2E31;Avst Cari Geor Hung Kthi Lydi Samr") else none
      else if c == 0x2E3C then some ("2E3C;Dupl")
      else
        if c < 0x3013 then
          if c < 0x3003 then
            if c < 0x2FF0 then
              if c < 0x2E43 then
                if c == 0x2E41 then some ("2E41;Adlm Arab Hung") else none
              else if c == 0x2E43 then some ("2E43;Cyrl Glag")
              else
                none
            else if c == 0x2FF0 then some ("2FFF;Hani Tang")
            else
              if c < 0x3002 then
                if c == 0x3001 then some ("3001;Bopo Hang Hani Hira Kana Mong Yiii") else none
              else if c == 0x3002 then some ("3002;Bopo Hang Hani Hira Kana Mong Phag Yiii")
              else
                none
          else if c == 0x3003 then some ("3003;Bopo Hang Hani Hira Kana")
          else
            if c < 0x300A then
              if c < 0x3008 then
                if c == 0x3006 then some ("3006;Hani") else none
              else if c == 0x3008 then some ("3009;Bopo Hang Hani Hira Kana Mong Tibt Yiii")
              else
                none
            else if c == 0x300A then some ("300B;Bopo Hang Hani Hira Kana Lisu Mong Tibt Yiii")
            else
              if c == 0x300C then some ("3011;Bopo Hang Hani Hira Kana Yiii") else none
        else if c == 0x3013 then some ("3013;Bopo Hang Hani Hira Kana")
        else
          if c < 0x3037 then
            if c < 0x302A then
              if c < 0x301C then
                if c == 0x3014 then some ("301B;Bopo Hang Hani Hira Kana Yiii") else none
              else if c == 0x301C then some ("301F;Bopo Hang Hani Hira Kana")
              else
                none
            else if c == 0x302A then some ("302D;Bopo Hani")
            else
              if c < 0x3031 then
                if c == 0x3030 then some ("3030;Bopo Hang Hani Hira Kana") else none
              else if c == 0x3031 then some ("3035;Hira Kana")
              else
                none
          else if c == 0x3037 then some ("3037;Bopo Hang Hani Hira Kana")
          else
            if c < 0x3099 then
              if c < 0x303E then
                if c == 0x303C then some ("303D;Hani Hira Kana") else none
              else if c == 0x303E then some ("303F;Hani")
              else
                none
            else if c == 0x3099 then some ("309C;Hira Kana")
            else
              if c == 0x30A0 then some ("30A0;Hira Kana") else none
    else if c == 0x30FB then some ("30FB;Bopo Hang Hani Hira Kana Yiii")
    else
      if c < 0xA9CF then
        if c < 0x33E0 then
          if c < 0x3280 then
            if c < 0x31C0 then
              if c < 0x3190 then
                if c == 0x30FC then some ("30FC;Hira Kana") else none
              else if c == 0x3190 then some ("319F;Hani")
              else
                none
            else if c == 0x31C0 then some ("31E5;Hani")
            else
              if c < 0x3220 then
                if c == 0x31EF then some ("31EF;Hani Tang") else none
              else if c == 0x3220 then some ("3247;Hani")
              else
                none
          else if c == 0x3280 then some ("32B0;Hani")
          else
            if c < 0x3358 then
              if c < 0x32FF then
                if c == 0x32C0 then some ("32CB;Hani") else none
              else if c == 0x32FF then some ("32FF;Hani")
              else
                none
            else if c == 0x3358 then some ("3370;Hani")
            else
              if c == 0x337B then some ("337F;Hani") else none
        else if c == 0x33E0 then some ("33FE;Hani")
        else
          if c < 0xA838 then
            if c < 0xA830 then
              if c < 0xA700 then
                if c == 0xA66F then some ("A66F;Cyrl Glag") else none
              else if c == 0xA700 then some ("A707;Hani Latn")
              else
                none
            else if c == 0xA830 then some ("A832;Deva Dogr Gujr Guru Khoj Knda Kthi Mahj Mlym Modi Nand Shrd Sind Takr Tirh Tutg")
            else
              if c < 0xA836 then
                if c == 0xA833 then some ("A835;Deva Dogr Gujr Guru Khoj Knda Kthi Mahj Modi Nand Shrd Sind Takr Tirh Tutg") else none
              else if c == 0xA836 then some ("A837;Deva Dogr Gujr Guru Khoj Kthi Mahj Modi Sind Takr Tirh")
              else
                none
          else if c == 0xA838 then some ("A838;Deva Dogr Gujr Guru Khoj Kthi Mahj Modi Shrd Sind Takr Tirh")
          else
            if c < 0xA8F3 then
              if c < 0xA8F1 then
                if c == 0xA839 then some ("A839;Deva Dogr Gujr Guru Khoj Kthi Mahj Modi Sind Takr Tirh") else none
              else if c == 0xA8F1 then some ("A8F1;Beng Deva Tutg")
              else
                none
            else if c == 0xA8F3 then some ("A8F3;Deva Taml")
            else
              if c == 0xA92E then some ("A92E;Kali Latn Mymr") else none
      else if c == 0xA9CF then some ("A9CF;Bugi Java")
      else
        if c < 0x10137 then
          if c < 0xFF70 then
            if c < 0xFDFD then
              if c < 0xFDF2 then
                if c == 0xFD3E then some ("FD3F;Arab Nkoo") else none
              else if c == 0xFDF2 then some ("FDF2;Arab Thaa")
              else
                none
            else if c == 0xFDFD then some ("FDFD;Arab Thaa")
            else
              if c < 0xFF61 then
                if c == 0xFE45 then some ("FE46;Bopo Hang Hani Hira Kana") else none
              else if c == 0xFF61 then some ("FF65;Bopo Hang Hani Hira Kana Yiii")
              else
                none
          else if c == 0xFF70 then some ("FF70;Hira Kana")
          else
            if c < 0x10102 then
              if c < 0x10100 then
                if c == 0xFF9E then some ("FF9F;Hira Kana") else none
              else if c == 0x10100 then some ("10101;Cpmn Cprt Linb")
              else
                none
            else if c == 0x10102 then some ("10102;Cprt Linb")
            else
              if c == 0x10107 then some ("10133;Cprt Lina Linb") else none
        else if c == 0x10137 then some ("1013F;Cprt Linb")
        else
          if c < 0x11FD0 then
            if c < 0x11301 then
              if c < 0x10AF2 then
                if c == 0x102E0 then some ("102FB;Arab Copt") else none
              else if c == 0x10AF2 then some ("10AF2;Mani Ougr")
              else
                none
            else if c == 0x11301 then some ("11301;Gran Taml")
            else
              if c < 0x1133B then
                if c == 0x11303 then some ("11303;Gran Taml") else none
              else if c == 0x1133B then some ("1133C;Gran Taml")
              else
                none
          else if c == 0x11FD0 then some ("11FD1;Gran Taml")
          else
            if c < 0x1D360 then
              if c < 0x1BCA0 then
                if c == 0x11FD3 then some ("11FD3;Gran Taml") else none
              else if c == 0x1BCA0 then some ("1BCA3;Dupl")
              else
                none
            else if c == 0x1D360 then some ("1D371;Hani")
            else
              if c == 0x1F250 then some ("1F251;Hani") else none

end Unicode.TableLookupTables.ScriptExtensions
