/- This file is generated by table-generators/makeTablesForLookupInLeanFromTablesTxt. -/
module
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace Unicode.TableLookupTables.WhiteSpace
private def table0 : Array (UInt32 × UInt32) := #[
  ((0x0009 : UInt32), (0x000D : UInt32)),
  ((0x0020 : UInt32), (0x0020 : UInt32)),
  ((0x0085 : UInt32), (0x0085 : UInt32)),
  ((0x00A0 : UInt32), (0x00A0 : UInt32)),
  ((0x1680 : UInt32), (0x1680 : UInt32)),
  ((0x2000 : UInt32), (0x200A : UInt32)),
  ((0x2028 : UInt32), (0x2028 : UInt32)),
  ((0x2029 : UInt32), (0x2029 : UInt32)),
  ((0x202F : UInt32), (0x202F : UInt32)),
  ((0x205F : UInt32), (0x205F : UInt32)),
  ((0x3000 : UInt32), (0x3000 : UInt32))
]

public def table : Array (UInt32 × UInt32) := Id.run do
  let mut t := #[]
  t := t ++ table0
  return t

end Unicode.TableLookupTables.WhiteSpace
