/- This file is generated by table-generators/makeTablesForLookup. -/
module

@[expose] public section

namespace Unicode

inductive ScriptName where
  | adlam
  | caucasianAlbanian
  | ahom
  | arabic
  | imperialAramaic
  | armenian
  | avestan
  | balinese
  | bamum
  | bassaVah
  | batak
  | bengali
  | beriaErfe
  | bhaiksuki
  | bopomofo
  | brahmi
  | braille
  | buginese
  | buhid
  | chakma
  | canadianAboriginal
  | carian
  | cham
  | cherokee
  | chorasmian
  | coptic
  | cyproMinoan
  | cypriot
  | cyrillic
  | devanagari
  | divesAkuru
  | dogra
  | deseret
  | duployan
  | egyptianHieroglyphs
  | elbasan
  | elymaic
  | ethiopic
  | garay
  | georgian
  | glagolitic
  | gunjalaGondi
  | masaramGondi
  | gothic
  | grantha
  | greek
  | gujarati
  | gurungKhema
  | gurmukhi
  | hangul
  | han
  | hanunoo
  | hatran
  | hebrew
  | hiragana
  | anatolianHieroglyphs
  | pahawhHmong
  | nyiakengPuachueHmong
  | katakanaOrHiragana
  | oldHungarian
  | oldItalic
  | javanese
  | kayahLi
  | katakana
  | kawi
  | kharoshthi
  | khmer
  | khojki
  | khitanSmallScript
  | kannada
  | kiratRai
  | kaithi
  | taiTham
  | lao
  | latin
  | lepcha
  | limbu
  | linearA
  | linearB
  | lisu
  | lycian
  | lydian
  | mahajani
  | makasar
  | mandaic
  | manichaean
  | marchen
  | medefaidrin
  | mendeKikakui
  | meroiticCursive
  | meroiticHieroglyphs
  | malayalam
  | modi
  | mongolian
  | mro
  | meeteiMayek
  | multani
  | myanmar
  | nagMundari
  | nandinagari
  | oldNorthArabian
  | nabataean
  | newa
  | nko
  | nushu
  | ogham
  | olChiki
  | olOnal
  | oldTurkic
  | oriya
  | osage
  | osmanya
  | oldUyghur
  | palmyrene
  | pauCinHau
  | oldPermic
  | phagsPa
  | inscriptionalPahlavi
  | psalterPahlavi
  | phoenician
  | miao
  | inscriptionalParthian
  | rejang
  | hanifiRohingya
  | runic
  | samaritan
  | oldSouthArabian
  | saurashtra
  | signwriting
  | shavian
  | sharada
  | siddham
  | sidetic
  | khudawadi
  | sinhala
  | sogdian
  | oldSogdian
  | soraSompeng
  | soyombo
  | sundanese
  | sunuwar
  | sylotiNagri
  | syriac
  | tagbanwa
  | takri
  | taiLe
  | newTaiLue
  | tamil
  | tangut
  | taiViet
  | taiYo
  | telugu
  | tifinagh
  | tagalog
  | thaana
  | thai
  | tibetan
  | tirhuta
  | tangsa
  | todhri
  | tolongSiki
  | toto
  | tuluTigalari
  | ugaritic
  | vai
  | vithkuqi
  | warangCiti
  | wancho
  | oldPersian
  | cuneiform
  | yezidi
  | yi
  | zanabazarSquare
  | inherited
  | common
  | unknown
  deriving DecidableEq, Inhabited, Repr

namespace ScriptName

public def toString : ScriptName → String
  | adlam => "Adlam"
  | caucasianAlbanian => "Caucasian_Albanian"
  | ahom => "Ahom"
  | arabic => "Arabic"
  | imperialAramaic => "Imperial_Aramaic"
  | armenian => "Armenian"
  | avestan => "Avestan"
  | balinese => "Balinese"
  | bamum => "Bamum"
  | bassaVah => "Bassa_Vah"
  | batak => "Batak"
  | bengali => "Bengali"
  | beriaErfe => "Beria_Erfe"
  | bhaiksuki => "Bhaiksuki"
  | bopomofo => "Bopomofo"
  | brahmi => "Brahmi"
  | braille => "Braille"
  | buginese => "Buginese"
  | buhid => "Buhid"
  | chakma => "Chakma"
  | canadianAboriginal => "Canadian_Aboriginal"
  | carian => "Carian"
  | cham => "Cham"
  | cherokee => "Cherokee"
  | chorasmian => "Chorasmian"
  | coptic => "Coptic"
  | cyproMinoan => "Cypro_Minoan"
  | cypriot => "Cypriot"
  | cyrillic => "Cyrillic"
  | devanagari => "Devanagari"
  | divesAkuru => "Dives_Akuru"
  | dogra => "Dogra"
  | deseret => "Deseret"
  | duployan => "Duployan"
  | egyptianHieroglyphs => "Egyptian_Hieroglyphs"
  | elbasan => "Elbasan"
  | elymaic => "Elymaic"
  | ethiopic => "Ethiopic"
  | garay => "Garay"
  | georgian => "Georgian"
  | glagolitic => "Glagolitic"
  | gunjalaGondi => "Gunjala_Gondi"
  | masaramGondi => "Masaram_Gondi"
  | gothic => "Gothic"
  | grantha => "Grantha"
  | greek => "Greek"
  | gujarati => "Gujarati"
  | gurungKhema => "Gurung_Khema"
  | gurmukhi => "Gurmukhi"
  | hangul => "Hangul"
  | han => "Han"
  | hanunoo => "Hanunoo"
  | hatran => "Hatran"
  | hebrew => "Hebrew"
  | hiragana => "Hiragana"
  | anatolianHieroglyphs => "Anatolian_Hieroglyphs"
  | pahawhHmong => "Pahawh_Hmong"
  | nyiakengPuachueHmong => "Nyiakeng_Puachue_Hmong"
  | katakanaOrHiragana => "Katakana_Or_Hiragana"
  | oldHungarian => "Old_Hungarian"
  | oldItalic => "Old_Italic"
  | javanese => "Javanese"
  | kayahLi => "Kayah_Li"
  | katakana => "Katakana"
  | kawi => "Kawi"
  | kharoshthi => "Kharoshthi"
  | khmer => "Khmer"
  | khojki => "Khojki"
  | khitanSmallScript => "Khitan_Small_Script"
  | kannada => "Kannada"
  | kiratRai => "Kirat_Rai"
  | kaithi => "Kaithi"
  | taiTham => "Tai_Tham"
  | lao => "Lao"
  | latin => "Latin"
  | lepcha => "Lepcha"
  | limbu => "Limbu"
  | linearA => "Linear_A"
  | linearB => "Linear_B"
  | lisu => "Lisu"
  | lycian => "Lycian"
  | lydian => "Lydian"
  | mahajani => "Mahajani"
  | makasar => "Makasar"
  | mandaic => "Mandaic"
  | manichaean => "Manichaean"
  | marchen => "Marchen"
  | medefaidrin => "Medefaidrin"
  | mendeKikakui => "Mende_Kikakui"
  | meroiticCursive => "Meroitic_Cursive"
  | meroiticHieroglyphs => "Meroitic_Hieroglyphs"
  | malayalam => "Malayalam"
  | modi => "Modi"
  | mongolian => "Mongolian"
  | mro => "Mro"
  | meeteiMayek => "Meetei_Mayek"
  | multani => "Multani"
  | myanmar => "Myanmar"
  | nagMundari => "Nag_Mundari"
  | nandinagari => "Nandinagari"
  | oldNorthArabian => "Old_North_Arabian"
  | nabataean => "Nabataean"
  | newa => "Newa"
  | nko => "Nko"
  | nushu => "Nushu"
  | ogham => "Ogham"
  | olChiki => "Ol_Chiki"
  | olOnal => "Ol_Onal"
  | oldTurkic => "Old_Turkic"
  | oriya => "Oriya"
  | osage => "Osage"
  | osmanya => "Osmanya"
  | oldUyghur => "Old_Uyghur"
  | palmyrene => "Palmyrene"
  | pauCinHau => "Pau_Cin_Hau"
  | oldPermic => "Old_Permic"
  | phagsPa => "Phags_Pa"
  | inscriptionalPahlavi => "Inscriptional_Pahlavi"
  | psalterPahlavi => "Psalter_Pahlavi"
  | phoenician => "Phoenician"
  | miao => "Miao"
  | inscriptionalParthian => "Inscriptional_Parthian"
  | rejang => "Rejang"
  | hanifiRohingya => "Hanifi_Rohingya"
  | runic => "Runic"
  | samaritan => "Samaritan"
  | oldSouthArabian => "Old_South_Arabian"
  | saurashtra => "Saurashtra"
  | signwriting => "SignWriting"
  | shavian => "Shavian"
  | sharada => "Sharada"
  | siddham => "Siddham"
  | sidetic => "Sidetic"
  | khudawadi => "Khudawadi"
  | sinhala => "Sinhala"
  | sogdian => "Sogdian"
  | oldSogdian => "Old_Sogdian"
  | soraSompeng => "Sora_Sompeng"
  | soyombo => "Soyombo"
  | sundanese => "Sundanese"
  | sunuwar => "Sunuwar"
  | sylotiNagri => "Syloti_Nagri"
  | syriac => "Syriac"
  | tagbanwa => "Tagbanwa"
  | takri => "Takri"
  | taiLe => "Tai_Le"
  | newTaiLue => "New_Tai_Lue"
  | tamil => "Tamil"
  | tangut => "Tangut"
  | taiViet => "Tai_Viet"
  | taiYo => "Tai_Yo"
  | telugu => "Telugu"
  | tifinagh => "Tifinagh"
  | tagalog => "Tagalog"
  | thaana => "Thaana"
  | thai => "Thai"
  | tibetan => "Tibetan"
  | tirhuta => "Tirhuta"
  | tangsa => "Tangsa"
  | todhri => "Todhri"
  | tolongSiki => "Tolong_Siki"
  | toto => "Toto"
  | tuluTigalari => "Tulu_Tigalari"
  | ugaritic => "Ugaritic"
  | vai => "Vai"
  | vithkuqi => "Vithkuqi"
  | warangCiti => "Warang_Citi"
  | wancho => "Wancho"
  | oldPersian => "Old_Persian"
  | cuneiform => "Cuneiform"
  | yezidi => "Yezidi"
  | yi => "Yi"
  | zanabazarSquare => "Zanabazar_Square"
  | inherited => "Inherited"
  | common => "Common"
  | unknown => "Unknown"

instance : ToString ScriptName where
  toString := toString

public def ofString? : String → Option ScriptName
  | "Adlam" => some adlam
  | "Caucasian_Albanian" => some caucasianAlbanian
  | "Ahom" => some ahom
  | "Arabic" => some arabic
  | "Imperial_Aramaic" => some imperialAramaic
  | "Armenian" => some armenian
  | "Avestan" => some avestan
  | "Balinese" => some balinese
  | "Bamum" => some bamum
  | "Bassa_Vah" => some bassaVah
  | "Batak" => some batak
  | "Bengali" => some bengali
  | "Beria_Erfe" => some beriaErfe
  | "Bhaiksuki" => some bhaiksuki
  | "Bopomofo" => some bopomofo
  | "Brahmi" => some brahmi
  | "Braille" => some braille
  | "Buginese" => some buginese
  | "Buhid" => some buhid
  | "Chakma" => some chakma
  | "Canadian_Aboriginal" => some canadianAboriginal
  | "Carian" => some carian
  | "Cham" => some cham
  | "Cherokee" => some cherokee
  | "Chorasmian" => some chorasmian
  | "Coptic" => some coptic
  | "Cypro_Minoan" => some cyproMinoan
  | "Cypriot" => some cypriot
  | "Cyrillic" => some cyrillic
  | "Devanagari" => some devanagari
  | "Dives_Akuru" => some divesAkuru
  | "Dogra" => some dogra
  | "Deseret" => some deseret
  | "Duployan" => some duployan
  | "Egyptian_Hieroglyphs" => some egyptianHieroglyphs
  | "Elbasan" => some elbasan
  | "Elymaic" => some elymaic
  | "Ethiopic" => some ethiopic
  | "Garay" => some garay
  | "Georgian" => some georgian
  | "Glagolitic" => some glagolitic
  | "Gunjala_Gondi" => some gunjalaGondi
  | "Masaram_Gondi" => some masaramGondi
  | "Gothic" => some gothic
  | "Grantha" => some grantha
  | "Greek" => some greek
  | "Gujarati" => some gujarati
  | "Gurung_Khema" => some gurungKhema
  | "Gurmukhi" => some gurmukhi
  | "Hangul" => some hangul
  | "Han" => some han
  | "Hanunoo" => some hanunoo
  | "Hatran" => some hatran
  | "Hebrew" => some hebrew
  | "Hiragana" => some hiragana
  | "Anatolian_Hieroglyphs" => some anatolianHieroglyphs
  | "Pahawh_Hmong" => some pahawhHmong
  | "Nyiakeng_Puachue_Hmong" => some nyiakengPuachueHmong
  | "Katakana_Or_Hiragana" => some katakanaOrHiragana
  | "Old_Hungarian" => some oldHungarian
  | "Old_Italic" => some oldItalic
  | "Javanese" => some javanese
  | "Kayah_Li" => some kayahLi
  | "Katakana" => some katakana
  | "Kawi" => some kawi
  | "Kharoshthi" => some kharoshthi
  | "Khmer" => some khmer
  | "Khojki" => some khojki
  | "Khitan_Small_Script" => some khitanSmallScript
  | "Kannada" => some kannada
  | "Kirat_Rai" => some kiratRai
  | "Kaithi" => some kaithi
  | "Tai_Tham" => some taiTham
  | "Lao" => some lao
  | "Latin" => some latin
  | "Lepcha" => some lepcha
  | "Limbu" => some limbu
  | "Linear_A" => some linearA
  | "Linear_B" => some linearB
  | "Lisu" => some lisu
  | "Lycian" => some lycian
  | "Lydian" => some lydian
  | "Mahajani" => some mahajani
  | "Makasar" => some makasar
  | "Mandaic" => some mandaic
  | "Manichaean" => some manichaean
  | "Marchen" => some marchen
  | "Medefaidrin" => some medefaidrin
  | "Mende_Kikakui" => some mendeKikakui
  | "Meroitic_Cursive" => some meroiticCursive
  | "Meroitic_Hieroglyphs" => some meroiticHieroglyphs
  | "Malayalam" => some malayalam
  | "Modi" => some modi
  | "Mongolian" => some mongolian
  | "Mro" => some mro
  | "Meetei_Mayek" => some meeteiMayek
  | "Multani" => some multani
  | "Myanmar" => some myanmar
  | "Nag_Mundari" => some nagMundari
  | "Nandinagari" => some nandinagari
  | "Old_North_Arabian" => some oldNorthArabian
  | "Nabataean" => some nabataean
  | "Newa" => some newa
  | "Nko" => some nko
  | "Nushu" => some nushu
  | "Ogham" => some ogham
  | "Ol_Chiki" => some olChiki
  | "Ol_Onal" => some olOnal
  | "Old_Turkic" => some oldTurkic
  | "Oriya" => some oriya
  | "Osage" => some osage
  | "Osmanya" => some osmanya
  | "Old_Uyghur" => some oldUyghur
  | "Palmyrene" => some palmyrene
  | "Pau_Cin_Hau" => some pauCinHau
  | "Old_Permic" => some oldPermic
  | "Phags_Pa" => some phagsPa
  | "Inscriptional_Pahlavi" => some inscriptionalPahlavi
  | "Psalter_Pahlavi" => some psalterPahlavi
  | "Phoenician" => some phoenician
  | "Miao" => some miao
  | "Inscriptional_Parthian" => some inscriptionalParthian
  | "Rejang" => some rejang
  | "Hanifi_Rohingya" => some hanifiRohingya
  | "Runic" => some runic
  | "Samaritan" => some samaritan
  | "Old_South_Arabian" => some oldSouthArabian
  | "Saurashtra" => some saurashtra
  | "SignWriting" => some signwriting
  | "Shavian" => some shavian
  | "Sharada" => some sharada
  | "Siddham" => some siddham
  | "Sidetic" => some sidetic
  | "Khudawadi" => some khudawadi
  | "Sinhala" => some sinhala
  | "Sogdian" => some sogdian
  | "Old_Sogdian" => some oldSogdian
  | "Sora_Sompeng" => some soraSompeng
  | "Soyombo" => some soyombo
  | "Sundanese" => some sundanese
  | "Sunuwar" => some sunuwar
  | "Syloti_Nagri" => some sylotiNagri
  | "Syriac" => some syriac
  | "Tagbanwa" => some tagbanwa
  | "Takri" => some takri
  | "Tai_Le" => some taiLe
  | "New_Tai_Lue" => some newTaiLue
  | "Tamil" => some tamil
  | "Tangut" => some tangut
  | "Tai_Viet" => some taiViet
  | "Tai_Yo" => some taiYo
  | "Telugu" => some telugu
  | "Tifinagh" => some tifinagh
  | "Tagalog" => some tagalog
  | "Thaana" => some thaana
  | "Thai" => some thai
  | "Tibetan" => some tibetan
  | "Tirhuta" => some tirhuta
  | "Tangsa" => some tangsa
  | "Todhri" => some todhri
  | "Tolong_Siki" => some tolongSiki
  | "Toto" => some toto
  | "Tulu_Tigalari" => some tuluTigalari
  | "Ugaritic" => some ugaritic
  | "Vai" => some vai
  | "Vithkuqi" => some vithkuqi
  | "Warang_Citi" => some warangCiti
  | "Wancho" => some wancho
  | "Old_Persian" => some oldPersian
  | "Cuneiform" => some cuneiform
  | "Yezidi" => some yezidi
  | "Yi" => some yi
  | "Zanabazar_Square" => some zanabazarSquare
  | "Inherited" => some inherited
  | "Common" => some common
  | "Unknown" => some unknown
  | _ => none

end ScriptName

end Unicode
